#ifndef __INC_AFFECT_H__
#define __INC_AFFECT_H__

class CAffect
{
public:
	DWORD dwType;
	POINT_TYPE wApplyOn;
	POINT_VALUE lApplyValue;
	DWORD dwFlag;
	long lDuration;
	long lSPCost;
#if defined(__AFFECT_RENEWAL__)
	bool bRealTime;
	bool bUpdate;
#endif
#if defined(__9TH_SKILL__)
	long lValue;
#endif

	static CAffect* Acquire();
	static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	//AFFECT_GUILD_SKILL_BLOOD = 152,
	//AFFECT_GUILD_SKILL_BLESS = 153,
	//AFFECT_GUILD_SKILL_SEONGHWI = 154,
	//AFFECT_GUILD_SKILL_ACCEL = 155,
	//AFFECT_GUILD_SKILL_BUNNO = 156,
	//AFFECT_GUILD_SKILL_JUMUN = 157,

	//AFFECT_SKILL_9_FINISH = 176,
	//AFFECT_SKILL_9_ILGWANGPYO = 177,
	//AFFECT_SKILL_9_PUNGLOEPO = 178,
	//AFFECT_SKILL_9_GEOMAGGWI = 179,
	//AFFECT_SKILL_9_MABEOBAGGWI = 180,
	//AFFECT_SKILL_9_METEO = 181,
#if defined(__9TH_SKILL__)
	AFFECT_SKILL_9_CHEONUN = 182,
#endif
	//AFFECT_SKILL_9_ILIPUNGU = 183,

	AFFECT_MOV_SPEED = 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,

	AFFECT_BLOCK_CHAT,
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,
	AFFECT_DEF_GRADE,

	AFFECT_BLEEDING,

	//AFFECT_SKILL_MONSTER_WIDE_AREA_DAMAGE_SUNGMA_STR = 274,
	//AFFECT_SKILL_MONSTER_ATT_GRADE_DOWN = 279,
	//AFFECT_SKILL_POSION_DAMAGE_SUNGMA_MOVE = 280,
	//AFFECT_SKILL_CRUSH_DAMAGE_SUNGMA_STR = 281,

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING = 301, // 라마단 이벤트용 특수아이템 초승달의 반지 착용 유무

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,

	AFFECT_PREMIUM_START = 500,
	AFFECT_EXP_BONUS = 500, // 경험의 반지
	AFFECT_ITEM_BONUS = 501, // 도둑의 장갑
	AFFECT_SAFEBOX = 502, // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT = 503, // PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND = 504, // PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST = 505, // 원앙의 깃털
	AFFECT_GOLD_BONUS = 506, // 돈 드롭확률 50%증가
	AFFECT_AUTO_USE = 507, // 자동 사냥
#if defined(__CONQUEROR_LEVEL__)
	AFFECT_SUNGMA_BONUS = 508,
#endif
	AFFECT_PREMIUM_END = 509,

	AFFECT_MALL = 510, // 몰 아이템 에펙트
	AFFECT_NO_DEATH_PENALTY = 511, // 용신의 가호 (경험치가 패널티를 한번 막아준다)
	AFFECT_SKILL_BOOK_BONUS = 512, // 선인의 교훈 (책 수련 성공 확률이 50% 증가)
	AFFECT_SKILL_NO_BOOK_DELAY = 513, // 주안술서

	AFFECT_HAIR = 514, // 헤어 효과
	AFFECT_COLLECT = 515, // 수집퀘스트 

	AFFECT_EXP_BONUS_EURO_FREE = 516, // 경험의 반지 (유럽 버전 14 레벨 이하 기본 효과)
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	//AFFECT_PREMIUM_PRIVATE_SHOP = 536,
#if defined(__LOOT_FILTER_SYSTEM__) && defined(__PREMIUM_LOOT_FILTER__)
	AFFECT_LOOTING_SYSTEM = 537,
#endif

	//AFFECT_UNKNOWN_538,
	//AFFECT_UNKNOWN_539,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,

	//AFFECT_PVP_EXPBONUS = 543,
	//AFFECT_IMPOSSIBLE_ATTACK = 544,
	//AFFECT_PVP_ENTER = 545,

#if defined(__SOUL_SYSTEM__)
	AFFECT_SOUL = 546,
#endif
	//AFFECT_UNKNOWN_547,
	//AFFECT_UNKNOWN_548,
	//AFFECT_UNKNOWN_549,

#if defined(__SET_ITEM__)
	AFFECT_SET_ITEM = 550,
#endif
	//AFFECT_EXP_BONUS_EVENT = 551,
	//AFFECT_ATT_SPEED_SLOW = 552,
	//AFFECT_PEPSI_EVENT = 553,
	//AFFECT_SUMMER_EVENT = 554,

	//AFFECT_BATTLE_FIELD = 555,
	//AFFECT_BATTLE_POTION = 556,
	//AFFECT_BATTLE_RANK = 557,

#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFFECT_RED_DRAGONLAIR_STONE = 558,
#endif
	//AFFECT_UNKNOWN_559,

	//AFFECT_LUCKEY_EVENT_BUFF = 560,
	AFFECT_MOUNT_FALL = 561,
	//AFFECT_NO_RECOVERY = 562,
	//AFFECT_REDUCE_CAST_SPEED = 563,
	//AFFECT_UNKNOWN_564,

	//AFFECT_ATT_GRADE_DOWN = 565,
	//AFFECT_DEF_GRADE_DOWN = 566,

	//AFFECT_CRITICAL_PCT_DOWN = 567,
	//AFFECT_CZ_UNLIMIT_ENTER = 568,
	//AFFECT_UNKNOWN_569,
#if defined(__FLOWER_EVENT__)
	AFFECT_FLOWER_EVENT = 570,
#endif
#if defined(__DS_SET__)
	AFFECT_DS_SET = 571,
#endif
	AFFECT_RESEARCHER_ELIXIR = 572,
#if defined(__DEFENSE_WAVE__)
	AFFECT_DEFENSEWAVE_LASER = 573,
#endif

	//AFFECT_NO_DEATH_PENALTY_PLUS = 574,
#if defined(__YUTNORI_EVENT_FLAG_RENEWAL__)
	AFFECT_HALLOWEEN_EVENT = 575,
#endif
	//AFFECT_UNKNOWN_576,
#if defined(__FISHING_GAME__)
	AFFECT_FISHING_GOLD_TUNA = 577,
	AFFECT_FISHING_MOVE_SPEED_DOWN = 578,
#endif
	//AFFECT_UNKNOWN_579,
	AFFECT_SAFE_BOX_BUFF = 580,
	//AFFECT_UNKNOWN_581,
	//AFFECT_MALL_EXP_BONUS = 582,

#if defined(__SUMMER_EVENT_ROULETTE__)
	AFFECT_LATE_SUMMER_EVENT_BUFF = 583,
	AFFECT_LATE_SUMMER_EVENT_PRIMIUM_BUFF = 584,
#endif

#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFFECT_RED_DRAGONLAIR_BUFF = 585,
#endif
	//AFFECT_MISTS_ISLAND_BUFF = 586,

	//AFFECT_SEASON_RANKING_BUFF = 587,
	//AFFECT_SEASON_PVE_BUFF = 588,
	//AFFECT_UNKNOWN_589,

	//AFFECT_BATTLE_ROYALE_SLOW = 590,
	//AFFECT_BATTLE_ROYALE_MOVE_SPEED = 591,
	//AFFECT_UNKNOWN_592,

	//AFFECT_PASSIVE_JOB_DECK = 593,
#if defined(__ELEMENTAL_DUNGEON__)
	AFFECT_CURSE_OF_ELEMENTAL = 594,
	AFFECT_PROTECTION_OF_ELEMENTAL = 595,
	AFFECT_POTION_OF_ELEMENTAL = 596,
#endif
	//AFFECT_UNKNOWN_597,
	//AFFECT_UNKNOWN_598,
	//AFFECT_UNKNOWN_599,
	//AFFECT_BATTLE_ROYALE_INFINITE_STAMINA = 600,

#if defined(__SET_ITEM__)
	AFFECT_SET_ITEM_SET_VALUE_1 = 601,
	AFFECT_SET_ITEM_SET_VALUE_2 = 602,
	AFFECT_SET_ITEM_SET_VALUE_3 = 603,
	AFFECT_SET_ITEM_SET_VALUE_4 = 604,
	AFFECT_SET_ITEM_SET_VALUE_5 = 605,
#endif
	//AFFECT_UNKNOWN_606,
	//AFFECT_UNKNOWN_607,

#if defined(__9TH_SKILL__)
	AFFECT_CHEONUN_INVINCIBILITY = 608,
#endif

	//AFFECT_WORLD_BOSS_REWARD = 609,
	//AFFECT_WORLD_BOSS_DAILY_REWARD = 610,

	//AFFECT_SUNGMAHEE_TOWER_BUFF = 611,
	//AFFECT_SUNGMAHEE_TOWER_DEBUFF = 612,
	//AFFECT_SUNGMAHEE_TOWER_CURSE = 613,
	//AFFECT_UNKNOWN_614,
	//AFFECT_GARRISON_DEBUFF = 615,
	//AFFECT_GARRISON_BUFF = 616,

	//AFFECT_UNKNOWN_617,
	//AFFECT_UNKNOWN_618,
	//AFFECT_UNKNOWN_619,
	//AFFECT_UNKNOWN_620,
	//AFFECT_UNKNOWN_621,
	//AFFECT_UNKNOWN_622,

#if defined(__CONQUEROR_LEVEL__)
	AFFECT_SUNGMA_STR = 623,
	AFFECT_SUNGMA_HP = 624,
	AFFECT_SUNGMA_MOVE = 625,
	AFFECT_SUNGMA_IMMUNE = 626,
#endif

	//AFFECT_UNKNOWN_627,
	//AFFECT_UNKNOWN_628,
	//AFFECT_SUBQUEST_NEWWORLD_5 = 629,
	//AFFECT_WHITE_DRAGON_CAVE_CURSE = 630,

	//AFFECT_SECRET_DUNGEON_BUFF_POINT_C = 631,
	//AFFECT_SECRET_DUNGEON_BUFF_C = 632,
	//AFFECT_SECRET_DUNGEON_BUFF_B = 633,
	//AFFECT_SECRET_DUNGEON_BUFF_A = 634,

	//AFFECT_OTHER_WORLD_DEAD_SOUL = 635,
	//AFFECT_OTHER_WORLD_GOBLIN_PROTECTION = 636,
	//AFFECT_OTHER_WORLD_YEOMWANG_CURSE = 637,
	//AFFECT_OTHER_WORLD_NORTH_REAPER_ROOM_DEBUFF = 638,

	//AFFECT_SKILL_MOUNT_UPGRADE_NIMBLE = 639,
	//AFFECT_SKILL_MOUNT_UPGRADE_EXP = 640,
	//AFFECT_SKILL_MOUNT_UPGRADE_SPEED = 641,
	//AFFECT_SKILL_MOUNT_UPGRADE_GYENONGGONG = 642,
	//AFFECT_SKILL_MOUNT_UPGRADE_INVINCIBLITIY = 643,
	//AFFECT_SKILL_MOUNT_UPGRADE_KNOCKBACK = 644,
	//AFFECT_SKILL_MOUNT_UPGRADE_TO_STRONG = 645,
	//AFFECT_SKILL_MOUNT_UPGRADE_EFFECT_UP = 646,
	//AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_STR = 647,
	//AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_HP = 648,
	//AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_MOVE = 649,
	//AFFECT_SKILL_MOUNT_UPGRADE_SUNGMA_IMMUNE = 650,
	//AFFECT_SKILL_MOUNT_UPGRADE_HIT_PCT = 651,

	//AFFECT_MERCENARY_MISSION_MAX_ACTIVE_INCREASE = 652,
	//AFFECT_SECRET_DUNGEON_BUFF_POINT_B = 653,
	//AFFECT_SECRET_DUNGEON_BUFF_POINT_A = 654,
	AFFECT_ELEMENT_BUFF_CRACK = 655,
	//AFFECT_FLOWER_OF_GALE = 656,
	//AFFECT_FLOWER_OF_DESTRUCTION = 657,
	//AFFECT_UNKNOWN_658,
	//AFFECT_UNKNOWN_659,
	//AFFECT_UNKNOWN_660,
	//AFFECT_UNKNOWN_661,
	//AFFECT_IMMUNE_MINE_TOWER_SKILL = 662,
#if defined(__SNOWFLAKE_STICK_EVENT__)
	AFFECT_SNOWFLAKE_STICK_EVENT_RANK_BUFF = 663,
	AFFECT_SNOWFLAKE_STICK_EVENT_SNOWFLAKE_BUFF = 664,
#endif

	AFFECT_QUEST_START_IDX = 1000,

	AFFECT_MAX
};

enum EAffectBits
{
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY, // 던전에서 준비 상태
	AFF_DUNGEON_UNIQUE, // 던전 유니크 (클라이언트에서 컬링되지않음)

	AFF_BUILDING_CONSTRUCTION_SMALL, // AFF_SHACKLE
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_JEONGWIHON, // 전귀혼
	AFF_GEOMGYEONG, // 검경
	AFF_CHEONGEUN, // 천근추
	AFF_GYEONGGONG, // 경공술
	AFF_EUNHYUNG, // 은형법
	AFF_GWIGUM, // 귀검
	AFF_TERROR, // 공포
	AFF_JUMAGAP, // 주마갑
	AFF_HOSIN, // 호신
	AFF_BOHO, // 보호
	AFF_KWAESOK, // 쾌속
	AFF_MANASHIELD, // 마나쉴드
	AFF_MUYEONG, // 무영진 affect
	AFF_REVIVE_INVISIBLE, // 부활시 잠시동안 무적
	AFF_FIRE, // 지속 불 데미지
	AFF_GICHEON, // 기천대공
	AFF_JEUNGRYEOK, // 증력술
	AFF_TANHWAN_DASH, // 탄환격용 달리기어펙트
	AFF_PABEOP, // 파법술
	AFF_CHEONGEUN_WITH_FALL, // 천근추

	AFF_POLYMORPH, // 폴리모프

	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,

	AFF_CHINA_FIREWORK,
	AFF_CANNOT_ATTACK,
	AFF_CANNOT_USE_SKILL,
	AFF_DS,

	AFF_BLEEDING,
	AFF_RED_POSSESSION,
	AFF_BLUE_POSSESSION,

	AFF_UNK46,
	AFF_UNK47,
#if defined(__GUILD_DRAGONLAIR_SYSTEM__)
	AFF_UNBEATABLE,
#endif

	AFF_BATTLE_FIELD_RANK1,
	AFF_BATTLE_FIELD_RANK2,
	AFF_BATTLE_FIELD_RANK3,
	AFF_TARGET_VICTIM,

	AFF_UNK53,

	AFF_ELECTRIC_SHOCK,
	AFF_CONFUSION,

#if defined(__SOUL_SYSTEM__)
	AFF_SOUL_RED,
	AFF_SOUL_BLUE,
	AFF_SOUL_MIX,
#endif

	AFF_UNK59,
	AFF_BATTLE_ROYALE_SLOW_1,
	AFF_BATTLE_ROYALE_SLOW_2,
	AFF_BATTLE_ROYALE_SLOW_3,

	AFF_UNK63,
	AFF_PASWAE,
	AFF_UNK65,

	AFF_ELEMENT_BUFF_CRACK_NONE,
	AFF_ELEMENT_BUFF_CRACK_FIRE,
	AFF_ELEMENT_BUFF_CRACK_ICE,
	AFF_ELEMENT_BUFF_CRACK_ELECT,
	AFF_ELEMENT_BUFF_CRACK_WIND,
	AFF_ELEMENT_BUFF_CRACK_EARTH,
	AFF_ELEMENT_BUFF_CRACK_DARK,

	AFF_FLAG_UNK73, // guild_battle (blue)
	AFF_FLAG_UNK74, // guild_battle (yellow)
	AFF_FLAG_UNK75, // guild_battle (green)
	AFF_FLAG_UNK76, // guild_battle (red)

	AFF_FLAG_UNK77,
	AFF_FLAG_UNK78,
	AFF_FLAG_UNK79,
	AFF_FLAG_UNK80,

#if defined(__9TH_SKILL__)
	AFF_CHEONUN_INVINCIBILITY,
	AFF_CHEONUN_NORMAL,
	AFF_CHEONUN_MASTER,
	AFF_CHEONUN_GRAND_MASTER,
	AFF_CHEONUN_PERFECT_MASTER,
#endif

	AFF_BITS_MAX,

	AFF_HWAYEOM = AFF_GEOMGYEONG,
};

extern void SendAffectAddPacket(LPDESC d, CAffect* pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Used when Affect should be set to infinity.
	// Since time continues to decrease, infinity is emulated by using a very large value.
	//// 24 bits are not enough, so 25 bits are used.
	// ...Despite saying to use 25 bits, this is an enormous comment using 29 bits...
	// In the collect quest, an infinite time of 60 years is used, so let's use 60 years here too.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif // __INC_AFFECT_H__
