#include "stdafx.h"
#include "char.h"

TJobInitialPoints JobInitialPoints[JOB_MAX_NUM] =
/*
{
	int st, ht, dx, iq;
	int max_hp, max_sp;
	int hp_per_ht, sp_per_iq;
	int hp_per_lv_begin, hp_per_lv_end;
	int sp_per_lv_begin, sp_per_lv_end;
	int max_stamina;
	int stamina_per_con;
	int stamina_per_lv_begin, stamina_per_lv_end;
}
*/
{
	//	str	con	dex	int	초기HP	초기SP	CON/HP	INT/SP	HP랜덤/lv	MP랜덤/lv	초기stam	stam/con	stam/lv
	{	 6,	4,	3,	3,	600,	200,	40,		20,		36,	44,		18,	22,		800,		5,			1,	3 }, // JOB_WARRIOR 16
	{	 4,	3,	6,	3,	650,	200,	40,		20,		36,	44,		18,	22,		800,		5,			1,	3 }, // JOB_ASSASSIN 16
	{	 5,	3,	3,	5,	650,	200,	40,		20,		36,	44,		18,	22,		800,		5,			1,	3 }, // JOB_SURA 16
	{	 3,	4,	3,	6,	700,	200,	40,		20,		36,	44,		18,	22,		800,		5,			1,	3 }, // JOB_SHAMAN 16
	{	 2,	6,	6,	2,	600,	200,	40,		20,		36,	44,		18,	22,		800,		5,			1,	3 }, // JOB_WOLFMAN 16
};

const TMobRankStat MobRankStats[MOB_RANK_MAX_NUM] =
/*
{
	int iGoldPercent;
}
*/
{
	{ 20, }, // MOB_RANK_PAWN,
	{ 20, }, // MOB_RANK_S_PAWN,
	{ 25, }, // MOB_RANK_KNIGHT,
	{ 30, }, // MOB_RANK_S_KNIGHT,
	{ 50, }, // MOB_RANK_BOSS,
	{ 100, } // MOB_RANK_KING,
};

TBattleTypeStat BattleTypeStats[BATTLE_TYPE_MAX_NUM] =
/*
{
	int AttGradeBias;
	int DefGradeBias;
	int MagicAttGradeBias;
	int MagicDefGradeBias;
}
*/
{
	{ 0, 0, 0, -10 }, // BATTLE_TYPE_MELEE,
	{ 10, -20, -10, -15 }, // BATTLE_TYPE_RANGE,
	{ -5, -5, 10, 10 }, // BATTLE_TYPE_MAGIC,
	{ 0, 0, 0, 0 }, // BATTLE_TYPE_SPECIAL,
	{ 10, -10, 0, -15 }, // BATTLE_TYPE_POWER,
	{ -10, 10, -10, 0 }, // BATTLE_TYPE_TANKER,
	{ 20, -20, 0, -10 }, // BATTLE_TYPE_SUPER_POWER,
	{ -20, 20, -10, 0 }, // BATTLE_TYPE_SUPER_TANKER,
};

const DWORD* exp_table = NULL;
const DWORD exp_table_common[PLAYER_EXP_TABLE_MAX + 1] =
{
	0, // 0
	300,
	800,
	1500,
	2500,
	4300,
	7200,
	11000,
	17000,
	24000,
	33000, // 10
	43000,
	58000,
	76000,
	100000,
	130000,
	169000,
	219000,
	283000,
	365000,
	472000, // 20
	610000,
	705000,
	813000,
	937000,
	1077000,
	1237000,
	1418000,
	1624000,
	1857000,
	2122000, // 30
	2421000,
	2761000,
	3145000,
	3580000,
	4073000,
	4632000,
	5194000,
	5717000,
	6264000,
	6837000, // 40
	7600000,
	8274000,
	8990000,
	9753000,
	10560000,
	11410000,
	12320000,
	13270000,
	14280000,
	15340000, // 50
	16870000,
	18960000,
	19980000,
	21420000,
	22930000,
	24530000,
	26200000,
	27960000,
	29800000,
	32780000, // 60
	36060000,
	39670000,
	43640000,
	48000000,
	52800000,
	58080000,
	63890000,
	70280000,
	77310000,
	85040000, // 70
	93540000,
	102900000,
	113500000,
	121000000,
	137000000,
	150700000,
	165700000,
	236990000,
	260650000,
	286780000, // 80
	315000000,
	346970000,
	381680000,
	419770000,
	461760000,
	508040000,
	558740000,
	614640000,
	676130000,
	743730000, // 90
	1041222000,
	1145344200,
	1259878620,
	1385866482,
	1524453130,
	1676898443,
	1844588288,
	2029047116,
	2050000000, // 99레벨 일 때 필요경험치 (100레벨이 되기 위한)
	2150000000, // 100
	2210000000,
	2250000000,
	2280000000,
	2310000000,
	2340000000,
	2370000000,
	2400000000,
	2430000000,
	2460000000,
	2490000000, // 110
	2520000000,
	2550000000,
	2580000000,
	2610000000,
	2640000000,
	2670000000,
	2700000000,
	2730000000,
	2760000000,
	2790000000, // 120
};

#if defined(__CONQUEROR_LEVEL__)
const DWORD* conqueror_exp_table = NULL;
const DWORD conqueror_exp_table_common[PLAYER_CONQUEROR_EXP_TABLE_MAX + 1] =
{
	0, // 0
	433400,
	1300204,
	2600413,
	4334029,
	6501054,
	9101490,
	12135339,
	15602603,
	19503284,
	23837384, // 10
	28604905,
	33805849,
	39440218,
	45508014,
	52009239,
	58943895,
	66311984,
	74113508,
	82348469,
	91016869, // 20
	100118710,
	109653994,
	119622723,
	130024899,
	140860524,
	152129600,
	163832129,
	175968113,
	188537554,
	188537554, // 30
};
#endif

const int* aiPercentByDeltaLev = NULL;
const int* aiPercentByDeltaLevForBoss = NULL;

// 적과 나와의 레벨차이에 의한 계산에 사용되는 테이블
// MIN(MAX_EXP_DELTA_OF_LEV - 1, (적렙 + 15) - 내렙))
const int aiPercentByDeltaLevForBoss_euckr[MAX_EXP_DELTA_OF_LEV] =
{
	1,		// -15	0
	3,		// -14	1
	5,		// -13	2
	7,		// -12	3
	15,		// -11	4
	30,		// -10	5
	60,		// -9	6
	90,		// -8	7
	91,		// -7	8
	92,		// -6	9
	93,		// -5	10
	94,		// -4	11
	95,		// -3	12
	97,		// -2	13
	99,		// -1	14
	100,	// 0	15
	105,	// 1	16
	110,	// 2	17
	115,	// 3	18
	120,	// 4	19
	125,	// 5	20
	130,	// 6	21
	135,	// 7	22
	140,	// 8	23
	145,	// 9	24
	150,	// 10	25
	155,	// 11	26
	160,	// 12	27
	165,	// 13	28
	170,	// 14	29
	180,	// 15	30
};

const int aiPercentByDeltaLev_euckr[MAX_EXP_DELTA_OF_LEV] =
{
	1,		// -15	0
	5,		// -14	1
	10,		// -13	2
	20,		// -12	3
	30,		// -11	4
	50,		// -10	5
	70,		// -9	6
	80,		// -8	7
	85,		// -7	8
	90,		// -6	9
	92,		// -5	10
	94,		// -4	11
	96,		// -3	12
	98,		// -2	13
	100,	// -1	14
	100,	// 0	15
	105,	// 1	16
	110,	// 2	17
	115,	// 3	18
	120,	// 4	19
	125,	// 5	20
	130,	// 6	21
	135,	// 7	22
	140,	// 8	23
	145,	// 9	24
	150,	// 10	25
	155,	// 11	26
	160,	// 12	27
	165,	// 13	28
	170,	// 14	29
	180,	// 15	30
};

const DWORD party_exp_distribute_table[PLAYER_MAX_LEVEL_CONST + 1] =
{
	0,
	10,		10,		10,		10,		15,		15,		20,		25,		30,		40,		// 1 - 10
	50,		60,		80,		100,	120,	140,	160,	184,	210,	240,	// 11 - 20
	270,	300,	330,	360,	390,	420,	450,	480,	510,	550,	// 21 - 30
	600,	640,	700,	760,	820,	880,	940,	1000,	1100,	1180,	// 31 - 40
	1260,	1320,	1380,	1440,	1500,	1560,	1620,	1680,	1740,	1800,	// 41 - 50
	1860,	1920,	2000,	2100,	2200,	2300,	2450,	2600,	2750,	2900,	// 51 - 60
	3050,	3200,	3350,	3500,	3650,	3800,	3950,	4100,	4250,	4400,	// 61 - 70
	4600,	4800,	5000,	5200,	5400,	5600,	5800,	6000,	6200,	6400,	// 71 - 80
	6600,	6900,	7100,	7300,	7600,	7800,	8000,	8300,	8500,	8800,	// 81 - 90
	9000,	9000,	9000,	9000,	9000,	9000,	9000,	9000,	9000,	9000,	// 91 - 100
	10000,	10000,	10000,	10000,	10000,	10000,	10000,	10000,	10000,	10000,	// 101 - 110
	12000,	12000,	12000,	12000,	12000,	12000,	12000,	12000,	12000,	12000,	// 111 - 120
};

Coord aArroundCoords[ARROUND_COORD_MAX_NUM] =
{
	{ 0, 0 },
	{ 0, 50 },
	{ 35, 35 },
	{ 50, -0 },
	{ 35, -35 },
	{ 0, -50 },
	{ -35, -35 },
	{ -50, 0 },
	{ -35, 35 },
	{ 0, 100 },
	{ 71, 71 },
	{ 100, -0 },
	{ 71, -71 },
	{ 0, -100 },
	{ -71, -71 },
	{ -100, 0 },
	{ -71, 71 },
	{ 0, 150 },
	{ 106, 106 },
	{ 150, -0 },
	{ 106, -106 },
	{ 0, -150 },
	{ -106, -106 },
	{ -150, 0 },
	{ -106, 106 },
	{ 0, 200 },
	{ 141, 141 },
	{ 200, -0 },
	{ 141, -141 },
	{ 0, -200 },
	{ -141, -141 },
	{ -200, 0 },
	{ -141, 141 },
	{ 0, 250 },
	{ 177, 177 },
	{ 250, -0 },
	{ 177, -177 },
	{ 0, -250 },
	{ -177, -177 },
	{ -250, 0 },
	{ -177, 177 },
	{ 0, 300 },
	{ 212, 212 },
	{ 300, -0 },
	{ 212, -212 },
	{ 0, -300 },
	{ -212, -212 },
	{ -300, 0 },
	{ -212, 212 },
	{ 0, 350 },
	{ 247, 247 },
	{ 350, -0 },
	{ 247, -247 },
	{ 0, -350 },
	{ -247, -247 },
	{ -350, 0 },
	{ -247, 247 },
	{ 0, 400 },
	{ 283, 283 },
	{ 400, -0 },
	{ 283, -283 },
	{ 0, -400 },
	{ -283, -283 },
	{ -400, 0 },
	{ -283, 283 },
	{ 0, 450 },
	{ 318, 318 },
	{ 450, -0 },
	{ 318, -318 },
	{ 0, -450 },
	{ -318, -318 },
	{ -450, 0 },
	{ -318, 318 },
	{ 0, 500 },
	{ 354, 354 },
	{ 500, -0 },
	{ 354, -354 },
	{ 0, -500 },
	{ -354, -354 },
	{ -500, 0 },
	{ -354, 354 },
	{ 0, 550 },
	{ 389, 389 },
	{ 550, -0 },
	{ 389, -389 },
	{ 0, -550 },
	{ -389, -389 },
	{ -550, 0 },
	{ -389, 389 },
	{ 0, 600 },
	{ 424, 424 },
	{ 600, -0 },
	{ 424, -424 },
	{ 0, -600 },
	{ -424, -424 },
	{ -600, 0 },
	{ -424, 424 },
	{ 0, 650 },
	{ 460, 460 },
	{ 650, -0 },
	{ 460, -460 },
	{ 0, -650 },
	{ -460, -460 },
	{ -650, 0 },
	{ -460, 460 },
	{ 0, 700 },
	{ 495, 495 },
	{ 700, -0 },
	{ 495, -495 },
	{ 0, -700 },
	{ -495, -495 },
	{ -700, 0 },
	{ -495, 495 },
	{ 0, 750 },
	{ 530, 530 },
	{ 750, -0 },
	{ 530, -530 },
	{ 0, -750 },
	{ -530, -530 },
	{ -750, 0 },
	{ -530, 530 },
	{ 0, 800 },
	{ 566, 566 },
	{ 800, -0 },
	{ 566, -566 },
	{ 0, -800 },
	{ -566, -566 },
	{ -800, 0 },
	{ -566, 566 },
	{ 0, 850 },
	{ 601, 601 },
	{ 850, -0 },
	{ 601, -601 },
	{ 0, -850 },
	{ -601, -601 },
	{ -850, 0 },
	{ -601, 601 },
	{ 0, 900 },
	{ 636, 636 },
	{ 900, -0 },
	{ 636, -636 },
	{ 0, -900 },
	{ -636, -636 },
	{ -900, 0 },
	{ -636, 636 },
	{ 0, 950 },
	{ 672, 672 },
	{ 950, -0 },
	{ 672, -672 },
	{ 0, -950 },
	{ -672, -672 },
	{ -950, 0 },
	{ -672, 672 },
	{ 0, 1000 },
	{ 707, 707 },
	{ 1000, -0 },
	{ 707, -707 },
	{ 0, -1000 },
	{ -707, -707 },
	{ -1000, 0 },
	{ -707, 707 },
};

const DWORD guild_exp_table[GUILD_MAX_LEVEL + 1] =
{
	0,
	15000UL,
	45000UL,
	90000UL,
	160000UL,
	235000UL,
	325000UL,
	430000UL,
	550000UL,
	685000UL,
	835000UL,
	1000000UL,
	1500000UL,
	2100000UL,
	2800000UL,
	3600000UL,
	4500000UL,
	6500000UL,
	8000000UL,
	10000000UL,
	42000000UL
};

// INTERNATIONAL_VERSION 길드경험치
const DWORD guild_exp_table2[GUILD_MAX_LEVEL + 1] =
{
	0,
	6000UL,
	18000UL,
	36000UL,
	64000UL,
	94000UL,
	130000UL,
	172000UL,
	220000UL,
	274000UL,
	334000UL,
	400000UL,
	600000UL,
	840000UL,
	1120000UL,
	1440000UL,
	1800000UL,
	2600000UL,
	3200000UL,
	4000000UL,
	16800000UL
};
// END_OF_INTERNATIONAL_VERSION 길드경험치

const int aiMobEnchantApplyIdx[MOB_ENCHANTS_MAX_NUM] =
{
	APPLY_CURSE_PCT,
	APPLY_SLOW_PCT,
	APPLY_POISON_PCT,
	APPLY_STUN_PCT,
	APPLY_CRITICAL_PCT,
	APPLY_PENETRATE_PCT,
};

const int aiMobResistsApplyIdx[MOB_RESISTS_MAX_NUM] =
{
	APPLY_RESIST_FIST,

	APPLY_RESIST_SWORD,
	APPLY_RESIST_TWOHAND,
	APPLY_RESIST_DAGGER,
	APPLY_RESIST_BELL,
	APPLY_RESIST_FAN,
	APPLY_RESIST_BOW,
	APPLY_RESIST_CLAW,

	APPLY_RESIST_FIRE,
	APPLY_RESIST_ELEC,
	APPLY_RESIST_MAGIC,
	APPLY_RESIST_WIND,

	APPLY_POISON_REDUCE,
	APPLY_BLEEDING_REDUCE,
};

#if defined(__ELEMENT_SYSTEM__)
const int aiMobElementsApplyIdx[MOB_ELEMENT_MAX_NUM] =
{
	APPLY_ENCHANT_ELECT,
	APPLY_ENCHANT_FIRE,
	APPLY_ENCHANT_ICE,
	APPLY_ENCHANT_WIND,
	APPLY_ENCHANT_EARTH,
	APPLY_ENCHANT_DARK
};
#endif

const int aiSocketPercentByQty[5][4] =
{
	{ 0, 0, 0, 0 },
	{ 3, 0, 0, 0 },
	{ 10, 1, 0, 0 },
	{ 15, 10, 1, 0 },
	{ 20, 15, 10, 1 }
};

const int aiWeaponSocketQty[WEAPON_NUM_TYPES] =
{
	3, // WEAPON_SWORD,
	3, // WEAPON_DAGGER,
	3, // WEAPON_BOW,
	3, // WEAPON_TWO_HANDED,
	3, // WEAPON_BELL,
	3, // WEAPON_FAN,
	0, // WEAPON_ARROW,
	0, // WEAPON_MOUNT_SPEAR
#if defined(__WOLFMAN_CHARACTER__)
	3, // WEAPON_CLAW
#endif
#if defined(__QUIVER_SYSTEM__)
	0, // WEAPON_QUIVER,
#endif
};

const int aiArmorSocketQty[ARMOR_NUM_TYPES] =
{
	3, // ARMOR_BODY,
	1, // ARMOR_HEAD,
	1, // ARMOR_SHIELD,
	0, // ARMOR_WRIST,
	0, // ARMOR_FOOTS,
	0 // ARMOR_ACCESSORY
};

#if defined(__AURA_COSTUME_SYSTEM__)
const int s_aiAuraRefineTable[AURA_GRADE_MAX_NUM][AURA_REFINE_INFO_MAX] = {
	// Grade					MinLevel	MaxLevel		Exp		MaterialVnum	MaterialCount	Cost		Pct
	{ AURA_GRADE_ORDINARY,		1,			49,				1000,	30617,			10,				5000000,	100 },
	{ AURA_GRADE_SIMPLE,		50,			99,				2000,	31136,			10,				5000000,	100 },
	{ AURA_GRADE_NOBLE,			100,		149,			4000,	31137,			10,				5000000,	100 },
	{ AURA_GRADE_SPARKLING,		150,		199,			8000,	31138,			10,				8000000,	100 },
	{ AURA_GRADE_MAGNIFICENT,	200,		249,			16000,	31138,			20,				10000000,	100 },
	{ AURA_GRADE_RADIANT,		250,		250,			0,		0,				0,				0,			0 },
	{ AURA_GRADE_NONE,			0,			0,				0,		0,				0,				0,			0 }
};

const int* GetAuraRefineInfo(BYTE bLevel)
{
	if (bLevel > AURA_MAX_LEVEL)
		return NULL;

	for (int i = 0; i < AURA_GRADE_MAX_NUM; ++i)
	{
		if (bLevel >= s_aiAuraRefineTable[i][AURA_REFINE_INFO_LEVEL_MIN] && bLevel <= s_aiAuraRefineTable[i][AURA_REFINE_INFO_LEVEL_MAX])
			return s_aiAuraRefineTable[i];
	}

	return NULL;
}

const int GetAuraRefineInfo(BYTE bGrade, BYTE bInfo)
{
	if (bGrade >= AURA_GRADE_MAX_NUM || bInfo >= AURA_REFINE_INFO_MAX)
		return 0;

	return s_aiAuraRefineTable[bGrade - 1][bInfo];
}
#endif

TItemAttrMap g_map_itemAttr;
TItemAttrMap g_map_itemRare;

const TApplyInfo aApplyInfo[MAX_APPLY_NUM] =
/*
{
	POINT_TYPE wApplyType;
	POINT_TYPE wPointType;
}
*/
{
	{ APPLY_NONE, POINT_NONE, },
	{ APPLY_MAX_HP, POINT_MAX_HP, },
	{ APPLY_MAX_SP, POINT_MAX_SP, },
	{ APPLY_CON, POINT_HT, },
	{ APPLY_INT, POINT_IQ, },
	{ APPLY_STR, POINT_ST, },
	{ APPLY_DEX, POINT_DX, },
	{ APPLY_ATT_SPEED, POINT_ATT_SPEED, },
	{ APPLY_MOV_SPEED, POINT_MOV_SPEED, },
	{ APPLY_CAST_SPEED, POINT_CASTING_SPEED, },
	{ APPLY_HP_REGEN, POINT_HP_REGEN, },
	{ APPLY_SP_REGEN, POINT_SP_REGEN, },
	{ APPLY_POISON_PCT, POINT_POISON_PCT, },
	{ APPLY_STUN_PCT, POINT_STUN_PCT, },
	{ APPLY_SLOW_PCT, POINT_SLOW_PCT, },
	{ APPLY_CRITICAL_PCT, POINT_CRITICAL_PCT, },
	{ APPLY_PENETRATE_PCT, POINT_PENETRATE_PCT, },
	{ APPLY_ATTBONUS_HUMAN, POINT_ATTBONUS_HUMAN, },
	{ APPLY_ATTBONUS_ANIMAL, POINT_ATTBONUS_ANIMAL, },
	{ APPLY_ATTBONUS_ORC, POINT_ATTBONUS_ORC, },
	{ APPLY_ATTBONUS_MILGYO, POINT_ATTBONUS_MILGYO, },
	{ APPLY_ATTBONUS_UNDEAD, POINT_ATTBONUS_UNDEAD, },
	{ APPLY_ATTBONUS_DEVIL, POINT_ATTBONUS_DEVIL, },
	{ APPLY_STEAL_HP, POINT_STEAL_HP, },
	{ APPLY_STEAL_SP, POINT_STEAL_SP, },
	{ APPLY_MANA_BURN_PCT, POINT_MANA_BURN_PCT, },
	{ APPLY_DAMAGE_SP_RECOVER, POINT_DAMAGE_SP_RECOVER, },
	{ APPLY_BLOCK, POINT_BLOCK, },
	{ APPLY_DODGE, POINT_DODGE, },
	{ APPLY_RESIST_SWORD, POINT_RESIST_SWORD, },
	{ APPLY_RESIST_TWOHAND, POINT_RESIST_TWOHAND, },
	{ APPLY_RESIST_DAGGER, POINT_RESIST_DAGGER, },
	{ APPLY_RESIST_BELL, POINT_RESIST_BELL, },
	{ APPLY_RESIST_FAN, POINT_RESIST_FAN, },
	{ APPLY_RESIST_BOW, POINT_RESIST_BOW, },
	{ APPLY_RESIST_FIRE, POINT_RESIST_FIRE, },
	{ APPLY_RESIST_ELEC, POINT_RESIST_ELEC, },
	{ APPLY_RESIST_MAGIC, POINT_RESIST_MAGIC, },
	{ APPLY_RESIST_WIND, POINT_RESIST_WIND, },
	{ APPLY_REFLECT_MELEE, POINT_REFLECT_MELEE, },
	{ APPLY_REFLECT_CURSE, POINT_REFLECT_CURSE, },
	{ APPLY_POISON_REDUCE, POINT_POISON_REDUCE, },
	{ APPLY_KILL_SP_RECOVER, POINT_KILL_SP_RECOVER, },
	{ APPLY_EXP_DOUBLE_BONUS, POINT_EXP_DOUBLE_BONUS, },
	{ APPLY_GOLD_DOUBLE_BONUS, POINT_GOLD_DOUBLE_BONUS, },
	{ APPLY_ITEM_DROP_BONUS, POINT_ITEM_DROP_BONUS, },
	{ APPLY_POTION_BONUS, POINT_POTION_BONUS, },
	{ APPLY_KILL_HP_RECOVER, POINT_KILL_HP_RECOVERY, },
	{ APPLY_IMMUNE_STUN, POINT_IMMUNE_STUN, },
	{ APPLY_IMMUNE_SLOW, POINT_IMMUNE_SLOW, },
	{ APPLY_IMMUNE_FALL, POINT_IMMUNE_FALL, },
	{ APPLY_SKILL, POINT_NONE, },
	{ APPLY_BOW_DISTANCE, POINT_BOW_DISTANCE, },
	{ APPLY_ATT_GRADE_BONUS, POINT_ATT_GRADE_BONUS, },
	{ APPLY_DEF_GRADE_BONUS, POINT_DEF_GRADE_BONUS, },
	{ APPLY_MAGIC_ATT_GRADE, POINT_MAGIC_ATT_GRADE_BONUS, },
	{ APPLY_MAGIC_DEF_GRADE, POINT_MAGIC_DEF_GRADE_BONUS, },
	{ APPLY_CURSE_PCT, POINT_CURSE_PCT, },
	{ APPLY_MAX_STAMINA, POINT_MAX_STAMINA, },
	{ APPLY_ATTBONUS_WARRIOR, POINT_ATTBONUS_WARRIOR, },
	{ APPLY_ATTBONUS_ASSASSIN, POINT_ATTBONUS_ASSASSIN, },
	{ APPLY_ATTBONUS_SURA, POINT_ATTBONUS_SURA, },
	{ APPLY_ATTBONUS_SHAMAN, POINT_ATTBONUS_SHAMAN, },
	{ APPLY_ATTBONUS_MONSTER, POINT_ATTBONUS_MONSTER, },
	{ APPLY_MALL_ATTBONUS, POINT_ATT_BONUS, },
	{ APPLY_MALL_DEFBONUS, POINT_MALL_DEFBONUS, },
	{ APPLY_MALL_EXPBONUS, POINT_MALL_EXPBONUS, },
	{ APPLY_MALL_ITEMBONUS, POINT_MALL_ITEMBONUS, },
	{ APPLY_MALL_GOLDBONUS, POINT_MALL_GOLDBONUS, },
	{ APPLY_MAX_HP_PCT, POINT_MAX_HP_PCT, },
	{ APPLY_MAX_SP_PCT, POINT_MAX_SP_PCT, },
	{ APPLY_SKILL_DAMAGE_BONUS, POINT_SKILL_DAMAGE_BONUS, },
	{ APPLY_NORMAL_HIT_DAMAGE_BONUS, POINT_NORMAL_HIT_DAMAGE_BONUS, },

	{ APPLY_SKILL_DEFEND_BONUS, POINT_SKILL_DEFEND_BONUS, },
	{ APPLY_NORMAL_HIT_DEFEND_BONUS, POINT_NORMAL_HIT_DEFEND_BONUS, },

	{ APPLY_PC_BANG_EXP_BONUS, POINT_PC_BANG_EXP_BONUS, },
	{ APPLY_PC_BANG_DROP_BONUS, POINT_PC_BANG_DROP_BONUS, },

	{ APPLY_EXTRACT_HP_PCT, POINT_NONE, },

	{ APPLY_RESIST_WARRIOR, POINT_RESIST_WARRIOR, },
	{ APPLY_RESIST_ASSASSIN, POINT_RESIST_ASSASSIN, },
	{ APPLY_RESIST_SURA, POINT_RESIST_SURA, },
	{ APPLY_RESIST_SHAMAN, POINT_RESIST_SHAMAN, },
	{ APPLY_ENERGY, POINT_ENERGY, },
	{ APPLY_DEF_GRADE, POINT_DEF_GRADE, },
	{ APPLY_COSTUME_ATTR_BONUS, POINT_COSTUME_ATTR_BONUS, },
	{ APPLY_MAGIC_ATTBONUS_PER, POINT_MAGIC_ATT_BONUS_PER, },
	{ APPLY_MELEE_MAGIC_ATTBONUS_PER, POINT_MELEE_MAGIC_ATT_BONUS_PER, },

	{ APPLY_RESIST_ICE, POINT_RESIST_ICE, },
	{ APPLY_RESIST_EARTH, POINT_RESIST_EARTH, },
	{ APPLY_RESIST_DARK, POINT_RESIST_DARK, },

	{ APPLY_ANTI_CRITICAL_PCT, POINT_RESIST_CRITICAL, },
	{ APPLY_ANTI_PENETRATE_PCT, POINT_RESIST_PENETRATE, },

	{ APPLY_BLEEDING_REDUCE, POINT_BLEEDING_REDUCE, },
	{ APPLY_BLEEDING_PCT, POINT_BLEEDING_PCT, },
	{ APPLY_ATTBONUS_WOLFMAN, POINT_ATTBONUS_WOLFMAN, },
	{ APPLY_RESIST_WOLFMAN, POINT_RESIST_WOLFMAN, },
	{ APPLY_RESIST_CLAW, POINT_RESIST_CLAW, },

	{ APPLY_ACCEDRAIN_RATE, POINT_NONE, },
#if defined(__MAGIC_REDUCTION__)
	{ APPLY_RESIST_MAGIC_REDUCTION, POINT_RESIST_MAGIC_REDUCTION, },
#endif

	{ APPLY_ENCHANT_ELECT, POINT_ENCHANT_ELECT, },
	{ APPLY_ENCHANT_FIRE, POINT_ENCHANT_FIRE, },
	{ APPLY_ENCHANT_ICE, POINT_ENCHANT_ICE, },
	{ APPLY_ENCHANT_WIND, POINT_ENCHANT_WIND, },
	{ APPLY_ENCHANT_EARTH, POINT_ENCHANT_EARTH, },
	{ APPLY_ENCHANT_DARK, POINT_ENCHANT_DARK, },

	{ APPLY_ATTBONUS_CZ, POINT_ATTBONUS_CZ, },
	{ APPLY_ATTBONUS_INSECT, POINT_ATTBONUS_INSECT, },
	{ APPLY_ATTBONUS_DESERT, POINT_ATTBONUS_DESERT, },
	{ APPLY_ATTBONUS_SWORD, POINT_ATTBONUS_SWORD, },
	{ APPLY_ATTBONUS_TWOHAND, POINT_ATTBONUS_TWOHAND, },
	{ APPLY_ATTBONUS_DAGGER, POINT_ATTBONUS_DAGGER, },
	{ APPLY_ATTBONUS_BELL, POINT_ATTBONUS_BELL, },
	{ APPLY_ATTBONUS_FAN, POINT_ATTBONUS_FAN, },
	{ APPLY_ATTBONUS_BOW, POINT_ATTBONUS_BOW, },
	{ APPLY_ATTBONUS_CLAW, POINT_ATTBONUS_CLAW, },

	{ APPLY_RESIST_HUMAN, POINT_RESIST_HUMAN, },
	{ APPLY_RESIST_MOUNT_FALL, POINT_RESIST_MOUNT_FALL, },
	{ APPLY_RESIST_FIST, POINT_RESIST_FIST, },

	{ APPLY_MOUNT, POINT_MOUNT, },

	{ APPLY_SKILL_DAMAGE_SAMYEON, POINT_SKILL_DAMAGE_SAMYEON, },
	{ APPLY_SKILL_DAMAGE_TANHWAN, POINT_SKILL_DAMAGE_TANHWAN, },
	{ APPLY_SKILL_DAMAGE_PALBANG, POINT_SKILL_DAMAGE_PALBANG, },
	{ APPLY_SKILL_DAMAGE_GIGONGCHAM, POINT_SKILL_DAMAGE_GIGONGCHAM, },
	{ APPLY_SKILL_DAMAGE_GYOKSAN, POINT_SKILL_DAMAGE_GYOKSAN, },
	{ APPLY_SKILL_DAMAGE_GEOMPUNG, POINT_SKILL_DAMAGE_GEOMPUNG, },
	{ APPLY_SKILL_DAMAGE_AMSEOP, POINT_SKILL_DAMAGE_AMSEOP, },
	{ APPLY_SKILL_DAMAGE_GUNGSIN, POINT_SKILL_DAMAGE_GUNGSIN, },
	{ APPLY_SKILL_DAMAGE_CHARYUN, POINT_SKILL_DAMAGE_CHARYUN, },
	{ APPLY_SKILL_DAMAGE_SANGONG, POINT_SKILL_DAMAGE_SANGONG, },
	{ APPLY_SKILL_DAMAGE_YEONSA, POINT_SKILL_DAMAGE_YEONSA, },
	{ APPLY_SKILL_DAMAGE_KWANKYEOK, POINT_SKILL_DAMAGE_KWANKYEOK, },
	{ APPLY_SKILL_DAMAGE_GIGUNG, POINT_SKILL_DAMAGE_GIGUNG, },
	{ APPLY_SKILL_DAMAGE_HWAJO, POINT_SKILL_DAMAGE_HWAJO, },
	{ APPLY_SKILL_DAMAGE_SWAERYUNG, POINT_SKILL_DAMAGE_SWAERYUNG, },
	{ APPLY_SKILL_DAMAGE_YONGKWON, POINT_SKILL_DAMAGE_YONGKWON, },
	{ APPLY_SKILL_DAMAGE_PABEOB, POINT_SKILL_DAMAGE_PABEOB, },
	{ APPLY_SKILL_DAMAGE_MARYUNG, POINT_SKILL_DAMAGE_MARYUNG, },
	{ APPLY_SKILL_DAMAGE_HWAYEOMPOK, POINT_SKILL_DAMAGE_HWAYEOMPOK, },
	{ APPLY_SKILL_DAMAGE_MAHWAN, POINT_SKILL_DAMAGE_MAHWAN, },
	{ APPLY_SKILL_DAMAGE_BIPABU, POINT_SKILL_DAMAGE_BIPABU, },
	{ APPLY_SKILL_DAMAGE_YONGBI, POINT_SKILL_DAMAGE_YONGBI, },
	{ APPLY_SKILL_DAMAGE_PAERYONG, POINT_SKILL_DAMAGE_PAERYONG, },
	{ APPLY_SKILL_DAMAGE_NOEJEON, POINT_SKILL_DAMAGE_NOEJEON, },
	{ APPLY_SKILL_DAMAGE_BYEURAK, POINT_SKILL_DAMAGE_BYEURAK, },
	{ APPLY_SKILL_DAMAGE_CHAIN, POINT_SKILL_DAMAGE_CHAIN, },
	{ APPLY_SKILL_DAMAGE_CHAYEOL, POINT_SKILL_DAMAGE_CHAYEOL, },
	{ APPLY_SKILL_DAMAGE_SALPOONG, POINT_SKILL_DAMAGE_SALPOONG, },
	{ APPLY_SKILL_DAMAGE_GONGDAB, POINT_SKILL_DAMAGE_GONGDAB, },
	{ APPLY_SKILL_DAMAGE_PASWAE, POINT_SKILL_DAMAGE_PASWAE, },

	{ APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE, POINT_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE, },
	{ APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE, POINT_SKILL_DEFEND_BONUS_BOSS_OR_MORE, },
	{ APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE, POINT_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE, },
	{ APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE, POINT_SKILL_DAMAGE_BONUS_BOSS_OR_MORE, },

	{ APPLY_HIT_BUFF_ENCHANT_FIRE, POINT_HIT_BUFF_ENCHANT_FIRE, },
	{ APPLY_HIT_BUFF_ENCHANT_ICE, POINT_HIT_BUFF_ENCHANT_ICE, },
	{ APPLY_HIT_BUFF_ENCHANT_ELEC, POINT_HIT_BUFF_ENCHANT_ELEC, },
	{ APPLY_HIT_BUFF_ENCHANT_WIND, POINT_HIT_BUFF_ENCHANT_WIND, },
	{ APPLY_HIT_BUFF_ENCHANT_DARK, POINT_HIT_BUFF_ENCHANT_DARK, },
	{ APPLY_HIT_BUFF_ENCHANT_EARTH, POINT_HIT_BUFF_ENCHANT_EARTH, },
	{ APPLY_HIT_BUFF_RESIST_FIRE, POINT_HIT_BUFF_RESIST_FIRE, },
	{ APPLY_HIT_BUFF_RESIST_ICE, POINT_HIT_BUFF_RESIST_ICE, },
	{ APPLY_HIT_BUFF_RESIST_ELEC, POINT_HIT_BUFF_RESIST_ELEC, },
	{ APPLY_HIT_BUFF_RESIST_WIND, POINT_HIT_BUFF_RESIST_WIND, },
	{ APPLY_HIT_BUFF_RESIST_DARK, POINT_HIT_BUFF_RESIST_DARK, },
	{ APPLY_HIT_BUFF_RESIST_EARTH, POINT_HIT_BUFF_RESIST_EARTH, },

	{ APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED, POINT_USE_SKILL_CHEONGRANG_MOV_SPEED, },
	{ APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED, POINT_USE_SKILL_CHEONGRANG_CASTING_SPEED, },
	{ APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT, POINT_USE_SKILL_CHAYEOL_CRITICAL_PCT, },
	{ APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS, POINT_USE_SKILL_SANGONG_ATT_GRADE_BONUS, },
	{ APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS, POINT_USE_SKILL_GIGUNG_ATT_GRADE_BONUS, },
	{ APPLY_USE_SKILL_JEOKRANG_DEF_BONUS, POINT_USE_SKILL_JEOKRANG_DEF_BONUS, },
	{ APPLY_USE_SKILL_GWIGEOM_DEF_BONUS, POINT_USE_SKILL_GWIGEOM_DEF_BONUS, },
	{ APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS, POINT_USE_SKILL_TERROR_ATT_GRADE_BONUS, },
	{ APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS, POINT_USE_SKILL_MUYEONG_ATT_GRADE_BONUS, },
	{ APPLY_USE_SKILL_MANASHILED_CASTING_SPEED, POINT_USE_SKILL_MANASHILED_CASTING_SPEED, },
	{ APPLY_USE_SKILL_HOSIN_DEF_BONUS, POINT_USE_SKILL_HOSIN_DEF_BONUS, },
	{ APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS, POINT_USE_SKILL_GICHEON_ATT_GRADE_BONUS, },
	{ APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS, POINT_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS, },
	{ APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS, POINT_USE_SKILL_JEUNGRYEOK_DEF_BONUS, },
	{ APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS, POINT_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS, },
	{ APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED, POINT_USE_SKILL_CHUNKEON_CASTING_SPEED, },
	{ APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS, POINT_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS, },

	{ APPLY_SKILL_DURATION_INCREASE_EUNHYUNG, POINT_SKILL_DURATION_INCREASE_EUNHYUNG, },
	{ APPLY_SKILL_DURATION_INCREASE_GYEONGGONG, POINT_SKILL_DURATION_INCREASE_GYEONGGONG, },
	{ APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG, POINT_SKILL_DURATION_INCREASE_GEOMKYUNG, },
	{ APPLY_SKILL_DURATION_INCREASE_JEOKRANG, POINT_SKILL_DURATION_INCREASE_JEOKRANG, },

	{ APPLY_USE_SKILL_PALBANG_HP_ABSORB, POINT_USE_SKILL_PALBANG_HP_ABSORB, },
	{ APPLY_USE_SKILL_AMSEOP_HP_ABSORB, POINT_USE_SKILL_AMSEOP_HP_ABSORB, },
	{ APPLY_USE_SKILL_YEONSA_HP_ABSORB, POINT_USE_SKILL_YEONSA_HP_ABSORB, },
	{ APPLY_USE_SKILL_YONGBI_HP_ABSORB, POINT_USE_SKILL_YONGBI_HP_ABSORB, },
	{ APPLY_USE_SKILL_CHAIN_HP_ABSORB, POINT_USE_SKILL_CHAIN_HP_ABSORB, },
	{ APPLY_USE_SKILL_PASWAE_SP_ABSORB, POINT_USE_SKILL_PASWAE_SP_ABSORB, },
	{ APPLY_USE_SKILL_GIGONGCHAM_STUN, POINT_USE_SKILL_GIGONGCHAM_STUN, },
	{ APPLY_USE_SKILL_CHARYUN_STUN, POINT_USE_SKILL_CHARYUN_STUN, },
	{ APPLY_USE_SKILL_PABEOB_STUN, POINT_USE_SKILL_PABEOB_STUN, },
	{ APPLY_USE_SKILL_MAHWAN_STUN, POINT_USE_SKILL_MAHWAN_STUN, },
	{ APPLY_USE_SKILL_GONGDAB_STUN, POINT_USE_SKILL_GONGDAB_STUN, },
	{ APPLY_USE_SKILL_SAMYEON_STUN, POINT_USE_SKILL_SAMYEON_STUN, },
	{ APPLY_USE_SKILL_GYOKSAN_KNOCKBACK, POINT_USE_SKILL_GYOKSAN_KNOCKBACK, },
	{ APPLY_USE_SKILL_SEOMJEON_KNOCKBACK, POINT_USE_SKILL_SEOMJEON_KNOCKBACK, },
	{ APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK, POINT_USE_SKILL_SWAERYUNG_KNOCKBACK, },
	{ APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK, POINT_USE_SKILL_HWAYEOMPOK_KNOCKBACK, },
	{ APPLY_USE_SKILL_GONGDAB_KNOCKBACK, POINT_USE_SKILL_GONGDAB_KNOCKBACK, },
	{ APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK, POINT_USE_SKILL_KWANKYEOK_KNOCKBACK, },
	{ APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER, },
	{ APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER, POINT_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER, },

	{ APPLY_ATTBONUS_STONE, POINT_ATTBONUS_STONE, },

	{ APPLY_DAMAGE_HP_RECOVERY, POINT_DAMAGE_HP_RECOVERY, },
	{ APPLY_DAMAGE_SP_RECOVERY, POINT_DAMAGE_SP_RECOVERY, },

	{ APPLY_ALIGNMENT_DAMAGE_BONUS, POINT_ALIGNMENT_DAMAGE_BONUS, },

	{ APPLY_NORMAL_DAMAGE_GUARD, POINT_NORMAL_DAMAGE_GUARD },
	{ APPLY_MORE_THEN_HP90_DAMAGE_REDUCE, POINT_MORE_THEN_HP90_DAMAGE_REDUCE, },

	{ APPLY_USE_SKILL_TUSOK_HP_ABSORB, POINT_USE_SKILL_TUSOK_HP_ABSORB, },
	{ APPLY_USE_SKILL_PAERYONG_HP_ABSORB, POINT_USE_SKILL_PAERYONG_HP_ABSORB, },
	{ APPLY_USE_SKILL_BYEURAK_HP_ABSORB, POINT_USE_SKILL_BYEURAK_HP_ABSORB, },

	{ APPLY_FIRST_ATTRIBUTE_BONUS, POINT_NONE, },
	{ APPLY_SECOND_ATTRIBUTE_BONUS, POINT_NONE, },
	{ APPLY_THIRD_ATTRIBUTE_BONUS, POINT_NONE, },
	{ APPLY_FOURTH_ATTRIBUTE_BONUS, POINT_NONE, },
	{ APPLY_FIFTH_ATTRIBUTE_BONUS, POINT_NONE, },

	{ APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER, POINT_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER, },
	{ APPLY_USE_SKILL_CHAYEOL_HP_ABSORB, POINT_USE_SKILL_CHAYEOL_HP_ABSORB, },

	{ APPLY_SUNGMA_STR, POINT_SUNGMA_STR, },
	{ APPLY_SUNGMA_HP, POINT_SUNGMA_HP, },
	{ APPLY_SUNGMA_MOVE, POINT_SUNGMA_MOVE, },
	{ APPLY_SUNGMA_IMMUNE, POINT_SUNGMA_IMMUNE, },

	{ APPLY_HIT_PCT, POINT_HIT_PCT, },
	{ APPLY_RANDOM, POINT_NONE, },

	{ APPLY_ATTBONUS_PER_HUMAN, POINT_ATTBONUS_PER_HUMAN, },
	{ APPLY_ATTBONUS_PER_ANIMAL, POINT_ATTBONUS_PER_ANIMAL, },
	{ APPLY_ATTBONUS_PER_ORC, POINT_ATTBONUS_PER_ORC, },
	{ APPLY_ATTBONUS_PER_MILGYO, POINT_ATTBONUS_PER_MILGYO, },
	{ APPLY_ATTBONUS_PER_UNDEAD, POINT_ATTBONUS_PER_UNDEAD, },
	{ APPLY_ATTBONUS_PER_DEVIL, POINT_ATTBONUS_PER_DEVIL, },

	{ APPLY_ENCHANT_PER_ELECT, POINT_ENCHANT_PER_ELECT, },
	{ APPLY_ENCHANT_PER_FIRE, POINT_ENCHANT_PER_FIRE, },
	{ APPLY_ENCHANT_PER_ICE, POINT_ENCHANT_PER_ICE, },
	{ APPLY_ENCHANT_PER_WIND, POINT_ENCHANT_PER_WIND, },
	{ APPLY_ENCHANT_PER_EARTH, POINT_ENCHANT_PER_EARTH, },
	{ APPLY_ENCHANT_PER_DARK, POINT_ENCHANT_PER_DARK, },

	{ APPLY_ATTBONUS_PER_CZ, POINT_ATTBONUS_PER_CZ, },
	{ APPLY_ATTBONUS_PER_INSECT, POINT_ATTBONUS_PER_INSECT, },
	{ APPLY_ATTBONUS_PER_DESERT, POINT_ATTBONUS_PER_DESERT, },
	{ APPLY_ATTBONUS_PER_STONE, POINT_ATTBONUS_PER_STONE, },
	{ APPLY_ATTBONUS_PER_MONSTER, POINT_ATTBONUS_PER_MONSTER, },

	{ APPLY_RESIST_PER_HUMAN, POINT_RESIST_PER_HUMAN, },
	{ APPLY_RESIST_PER_ICE, POINT_RESIST_PER_ICE, },
	{ APPLY_RESIST_PER_DARK, POINT_RESIST_PER_DARK, },
	{ APPLY_RESIST_PER_EARTH, POINT_RESIST_PER_EARTH, },
	{ APPLY_RESIST_PER_FIRE, POINT_RESIST_PER_FIRE, },
	{ APPLY_RESIST_PER_ELEC, POINT_RESIST_PER_ELEC, },
	{ APPLY_RESIST_PER_MAGIC, POINT_RESIST_PER_MAGIC, },
	{ APPLY_RESIST_PER_WIND, POINT_RESIST_PER_WIND, },

	{ APPLY_HIT_BUFF_SUNGMA_STR, POINT_HIT_BUFF_SUNGMA_STR, },
	{ APPLY_HIT_BUFF_SUNGMA_MOVE, POINT_HIT_BUFF_SUNGMA_MOVE, },
	{ APPLY_HIT_BUFF_SUNGMA_HP, POINT_HIT_BUFF_SUNGMA_HP, },
	{ APPLY_HIT_BUFF_SUNGMA_IMMUNE, POINT_HIT_BUFF_SUNGMA_IMMUNE, },

	{ APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER, POINT_MOUNT_MELEE_MAGIC_ATTBONUS_PER, },
	{ APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER, POINT_DISMOUNT_MOVE_SPEED_BONUS_PER, },

	{ APPLY_HIT_AUTO_HP_RECOVERY, POINT_HIT_AUTO_HP_RECOVERY, },
	{ APPLY_HIT_AUTO_SP_RECOVERY, POINT_HIT_AUTO_SP_RECOVERY, },

	{ APPLY_USE_SKILL_COOLTIME_DECREASE_ALL, POINT_USE_SKILL_COOLTIME_DECREASE_ALL, },

	{ APPLY_HIT_STONE_ATTBONUS_STONE, POINT_HIT_STONE_ATTBONUS_STONE, },
	{ APPLY_HIT_STONE_DEF_GRADE_BONUS, POINT_HIT_STONE_DEF_GRADE_BONUS, },

	{ APPLY_KILL_BOSS_ITEM_BONUS, POINT_KILL_BOSS_ITEM_BONUS, },
	{ APPLY_MOB_HIT_MOB_AGGRESSIVE, POINT_MOB_HIT_MOB_AGGRESSIVE, },
	{ APPLY_NO_DEATH_AND_HP_RECOVERY30, POINT_NO_DEATH_AND_HP_RECOVERY30, },

	{ APPLY_AUTO_PICKUP, POINT_AUTO_PICKUP, },
	{ APPLY_MOUNT_NO_KNOCKBACK, POINT_MOUNT_NO_KNOCKBACK, },

	{ APPLY_SUNGMA_PER_STR, POINT_SUNGMA_PER_STR, },
	{ APPLY_SUNGMA_PER_HP, POINT_SUNGMA_PER_HP, },
	{ APPLY_SUNGMA_PER_MOVE, POINT_SUNGMA_PER_MOVE, },
	{ APPLY_SUNGMA_PER_IMMUNE, POINT_SUNGMA_PER_IMMUNE, },

	{ APPLY_IMMUNE_POISON100, POINT_IMMUNE_POISON100, },
	{ APPLY_IMMUNE_BLEEDING100, POINT_IMMUNE_BLEEDING100, },

	{ APPLY_MONSTER_DEFEND_BONUS, POINT_MONSTER_DEFEND_BONUS, },
};

const int aiItemMagicAttributePercentHigh[ITEM_ATTRIBUTE_MAX_LEVEL] =
{
	//25, 25, 40, 8, 2,
	30, 40, 20, 8, 2
};

const int aiItemMagicAttributePercentLow[ITEM_ATTRIBUTE_MAX_LEVEL] =
{
	//45, 25, 20, 10, 0,
	50, 40, 10, 0, 0
};

// ADD_ITEM_ATTRIBUTE
const int aiItemAttributeAddPercent[ITEM_ATTRIBUTE_MAX_NUM] =
{
	100, 80, 60, 50, 30, 0, 0,
};
// END_OF_ADD_ITEM_ATTRIBUTE

const int aiExpLossPercents[PLAYER_EXP_TABLE_MAX + 1] =
{
	0,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 4, // 1 - 10
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4, // 11 - 20
	4, 4, 4, 4, 4, 4, 4, 3, 3, 3, // 21 - 30
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 31 - 40
	3, 3, 3, 3, 2, 2, 2, 2, 2, 2, // 41 - 50
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // 51 - 60
	2, 2, 1, 1, 1, 1, 1, 1, 1, 1, // 61 - 70
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 71 - 80
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 81 - 90
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 91 - 100
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 101 - 110
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, // 111 - 120
};

const int aiSkillBookCountForLevelUp[10] =
{
	3, 3, 3, 3, 3, 4, 4, 5, 5, 6
};

// ADD_GRANDMASTER_SKILL
const int aiGrandMasterSkillBookCountForLevelUp[10] =
{
	3, 3, 5, 5, 7, 7, 10, 10, 10, 20,
};

const int aiGrandMasterSkillBookMinCount[10] =
{
	// 1, 1, 3, 5, 10, 15, 20, 30, 40, 50,
	// 3, 3, 5, 5, 10, 10, 15, 15, 20, 30
	1, 1, 1, 2, 2, 3, 3, 4, 5, 6
};

const int aiGrandMasterSkillBookMaxCount[10] =
{
	// 6, 15, 30, 45, 60, 80, 100, 120, 160, 200,
	// 6, 10, 15, 20, 30, 40, 50, 60, 70, 80
	5, 7, 9, 11, 13, 15, 20, 25, 30, 35
};
// END_OF_ADD_GRANDMASTER_SKILL

const int CHN_aiPartyBonusExpPercentByMemberCount[9] =
{
	0, 0, 12, 18, 26, 40, 53, 70, 100
};

// UPGRADE_PARTY_BONUS
const int KOR_aiPartyBonusExpPercentByMemberCount[9] =
{
	0,
	0,
	30, // 66% * 2 - 100
	60, // 53% * 3 - 100
	75, // 44% * 4 - 100
	90, // 38% * 5 - 100
	105, // 34% * 6 - 100
	110, // 30% * 7 - 100
	140, // 30% * 8 - 100
};

const int KOR_aiUniqueItemPartyBonusExpPercentByMemberCount[9] =
{
	0,
	0,
	15 * 2,
	14 * 3,
	13 * 4,
	12 * 5,
	11 * 6,
	10 * 7,
	10 * 8,
};
// END_OF_UPGRADE_PARTY_BONUS

const int* aiChainLightningCountBySkillLevel = NULL;

const int aiChainLightningCountBySkillLevel_euckr[SKILL_MAX_LEVEL + 1] =
{
	0, // 0
	2, // 1
	2, // 2
	2, // 3
	2, // 4
	2, // 5
	2, // 6
	2, // 7
	2, // 8
	3, // 9
	3, // 10
	3, // 11
	3, // 12
	3, // 13
	3, // 14
	3, // 15
	3, // 16
	3, // 17
	3, // 18
	4, // 19
	4, // 20
	4, // 21
	4, // 22
	4, // 23
	5, // 24
	5, // 25
	5, // 26
	5, // 27
	5, // 28
	5, // 29
	5, // 30
	5, // 31
	5, // 32
	5, // 33
	5, // 34
	5, // 35
	5, // 36
	5, // 37
	5, // 38
	5, // 39
	5, // 40
};

const SStoneDropInfo aStoneDrop[STONE_INFO_MAX_NUM] =
{
	// mob pct { +0 +1 +2 +3 +4 }
	{ 8005, 60, { 30, 30, 30, 9, 1 } },
	{ 8006, 60, { 28, 29, 31, 11, 1 } },
	{ 8007, 60, { 24, 29, 32, 13, 2 } },
	{ 8008, 60, { 22, 28, 33, 15, 2 } },
	{ 8009, 60, { 21, 27, 33, 17, 2 } },
	{ 8010, 60, { 18, 26, 34, 20, 2 } },
	{ 8011, 60, { 14, 26, 35, 22, 3 } },
	{ 8012, 60, { 10, 26, 37, 24, 3 } },
	{ 8013, 60, { 2, 26, 40, 29, 3 } },
	{ 8014, 60, { 0, 26, 41, 30, 3 } },
	{ 8018, 60, { 0, 25, 42, 30, 3 } },
	{ 8019, 60, { 0, 23, 42, 32, 3 } },
	{ 8024, 60, { 0, 22, 43, 32, 3 } },
	{ 8025, 60, { 0, 21, 43, 32, 4 } },
	{ 8026, 60, { 0, 19, 44, 33, 4 } },
	{ 8027, 60, { 0, 17, 45, 34, 4 } },
	{ 8051, 60, { 0, 15, 46, 34, 5 } },
	{ 8052, 60, { 0, 15, 46, 34, 5 } },
	{ 8053, 60, { 0, 12, 47, 36, 5 } },
	{ 8054, 60, { 0, 12, 47, 36, 5 } },
	{ 8055, 60, { 0, 9, 48, 37, 6 } },
	{ 8056, 60, { 0, 9, 48, 37, 6 } },
};

const char* c_apszEmpireNames[EMPIRE_MAX_NUM] =
{
#if defined(__LOCALE_CLIENT__)
	"[LS;1037]",
	"[LS;793]",
	"[LS;794]",
	"[LS;795]"
#else
	"전제국",
	"신수국",
	"천조국",
	"진노국"
#endif
};

const char* c_apszPrivNames[MAX_PRIV_NUM] =
{
#if defined(__LOCALE_CLIENT__)
	"",
	"[LS;1038]",
	"[LS;1039]",
	"[LS;1031]",
	"[LS;1040]"
#else
	"",
	"아이템이 나올 확률",
	"돈이 나올 확률",
	"돈 대박이 나올 확률",
	"경험치 배율"
#endif
};

const int aiPolymorphPowerByLevel[SKILL_MAX_LEVEL + 1] =
{
	0, // 0
	10, // 1
	11, // 2
	11, // 3
	12, // 4
	13, // 5
	13, // 6
	14, // 7
	15, // 8
	16, // 9
	17, // 10
	18, // 11
	19, // 12
	20, // 13
	22, // 14
	23, // 15
	24, // 16
	26, // 17
	27, // 18
	29, // 19
	31, // 20 M1
	33, // 21
	35, // 22
	37, // 23
	39, // 24
	41, // 25
	44, // 26
	46, // 27
	49, // 28
	52, // 29
	55, // 30 G1
	59, // 31
	62, // 32
	66, // 33
	70, // 34
	74, // 35
	79, // 36
	84, // 37
	89, // 38
	94,	// 39
	100, // 40 P
};

#if defined(__PARTY_PROFICY__)
const int aiProficiencyPowerByLevel[SKILL_MAX_LEVEL + 1] = {
	0, 1, 2, 3, 4, 5, 6, 7,8, 9,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
	30, 32, 34, 36, 38, 40, 42, 44, 46, 48,
	50,
};
#endif

const int aiPrecisionPowerByLevel[SKILL_MAX_LEVEL + 1] =
{
	0,	// 0
	0,	// 1
	0,	// 2
	1,	// 3
	1,	// 4
	1,	// 5
	2,	// 6
	2,	// 7
	2,	// 8
	3,	// 9
	3,	// 10
	3,	// 11
	4,	// 12
	4,	// 13
	4,	// 14
	5,	// 15
	5,	// 16
	5,	// 17
	6,	// 18
	6,	// 19
	8,	// 20
	8,	// 21
	8,	// 22
	9,	// 23
	9,	// 24
	9,	// 25
	10,	// 26
	10,	// 27
	11,	// 28
	11,	// 29
	13,	// 30
	13,	// 31
	14,	// 32
	14,	// 33
	15,	// 34
	16,	// 35
	16,	// 36
	17,	// 37
	18,	// 38
	18,	// 39
	20,	// 40
};

TGuildWarInfo KOR_aGuildWarInfo[GUILD_WAR_TYPE_MAX_NUM] =
/*
{
	long lMapIndex;
	int iWarPrice;
	int iWinnerPotionRewardPctToWinner;
	int iLoserPotionRewardPctToWinner;
	int iInitialScore;
	int iEndScore;
};
*/
{
	{ 0, 0, 0, 0, 0, 0 },
	{ 110, 0, 100, 50, 0, 100 },
	{ 111, 0, 100, 50, 0, 10 },
};

//
// 악세서리 소켓용 수치들
//

// 다이아몬드로 소켓을 추가할 때 확률
const int aiAccessorySocketAddPct[ITEM_ACCESSORY_SOCKET_MAX_NUM] =
{
	50, 50, 50
};

// 악세서리 수치 값의 몇%만큼의 성능을 추가하는지
const int aiAccessorySocketEffectivePct[ITEM_ACCESSORY_SOCKET_MAX_NUM + 1] =
{
	0, 10, 20, 40
};

// 소켓 지속시간 24, 12, 6
const int aiAccessorySocketDegradeTime[ITEM_ACCESSORY_SOCKET_MAX_NUM + 1] =
{
	0, 3600 * 24, 3600 * 12, 3600 * 6
};

// 소켓 장착 성공률
const int aiAccessorySocketPutPct[ITEM_ACCESSORY_SOCKET_MAX_NUM + 1] =
{
	90, 80, 70, 0
};
// END_OF_ACCESSORY_REFINE

#if defined(__ACCE_COSTUME_SYSTEM__)
const int aiAcceDrainRateAdvancePct[ACCE_MAX_DRAINRATE + 1] =
{
	100, // 0
	100, // 1
	100, // 2
	100, // 3
	100, // 4
	100, // 5
	100, // 6
	100, // 7
	100, // 8
	100, // 9
	100, // 10
	100, // 11
	100, // 12
	100, // 13
	100, // 14
	100, // 15
	100, // 16
	90, // 17
	80, // 18
	50, // 19
	40, // 20
	35, // 21
	30, // 22
	25, // 23
	20, // 24
	0 // 25
};
#endif

#include "../../common/length.h"
// from import_item_proto.c
typedef struct SValueName
{
	const char* c_pszName;
	long lValue;
} TValueName;

TValueName c_aApplyTypeNames[] =
{
	// APPLY_NONE
	{ "MAX_HP", APPLY_MAX_HP },
	{ "MAX_SP", APPLY_MAX_SP },
	{ "CON", APPLY_CON },
	{ "INT", APPLY_INT },
	{ "STR", APPLY_STR },
	{ "DEX", APPLY_DEX },
	{ "ATT_SPEED", APPLY_ATT_SPEED },
	{ "MOV_SPEED", APPLY_MOV_SPEED },
	{ "CAST_SPEED", APPLY_CAST_SPEED },
	{ "HP_REGEN", APPLY_HP_REGEN },
	{ "SP_REGEN", APPLY_SP_REGEN },
	{ "POISON_PCT", APPLY_POISON_PCT },
	{ "STUN_PCT", APPLY_STUN_PCT },
	{ "SLOW_PCT", APPLY_SLOW_PCT },
	{ "CRITICAL_PCT", APPLY_CRITICAL_PCT },
	{ "PENETRATE_PCT", APPLY_PENETRATE_PCT },
	{ "ATTBONUS_HUMAN", APPLY_ATTBONUS_HUMAN },
	{ "ATTBONUS_ANIMAL", APPLY_ATTBONUS_ANIMAL },
	{ "ATTBONUS_ORC", APPLY_ATTBONUS_ORC },
	{ "ATTBONUS_MILGYO", APPLY_ATTBONUS_MILGYO },
	{ "ATTBONUS_UNDEAD", APPLY_ATTBONUS_UNDEAD },
	{ "ATTBONUS_DEVIL", APPLY_ATTBONUS_DEVIL },
	{ "STEAL_HP", APPLY_STEAL_HP },
	{ "STEAL_SP", APPLY_STEAL_SP },
	{ "MANA_BURN_PCT", APPLY_MANA_BURN_PCT },
	{ "DAMAGE_SP_RECOVER", APPLY_DAMAGE_SP_RECOVER },
	{ "BLOCK", APPLY_BLOCK },
	{ "DODGE", APPLY_DODGE },
	{ "RESIST_SWORD", APPLY_RESIST_SWORD },
	{ "RESIST_TWOHAND", APPLY_RESIST_TWOHAND },
	{ "RESIST_DAGGER", APPLY_RESIST_DAGGER },
	{ "RESIST_BELL", APPLY_RESIST_BELL },
	{ "RESIST_FAN", APPLY_RESIST_FAN },
	{ "RESIST_BOW", APPLY_RESIST_BOW },
	{ "RESIST_FIRE", APPLY_RESIST_FIRE },
	{ "RESIST_ELEC", APPLY_RESIST_ELEC },
	{ "RESIST_MAGIC", APPLY_RESIST_MAGIC },
	{ "RESIST_WIND", APPLY_RESIST_WIND },
	{ "REFLECT_MELEE", APPLY_REFLECT_MELEE },
	{ "REFLECT_CURSE", APPLY_REFLECT_CURSE },
	{ "POISON_REDUCE", APPLY_POISON_REDUCE },
	{ "KILL_SP_RECOVER", APPLY_KILL_SP_RECOVER },
	{ "EXP_DOUBLE_BONUS", APPLY_EXP_DOUBLE_BONUS },
	{ "GOLD_DOUBLE_BONUS", APPLY_GOLD_DOUBLE_BONUS },
	{ "ITEM_DROP_BONUS", APPLY_ITEM_DROP_BONUS },
	{ "POTION_BONUS", APPLY_POTION_BONUS },
	{ "KILL_HP_RECOVER", APPLY_KILL_HP_RECOVER },
	{ "IMMUNE_STUN", APPLY_IMMUNE_STUN },
	{ "IMMUNE_SLOW", APPLY_IMMUNE_SLOW },
	{ "IMMUNE_FALL", APPLY_IMMUNE_FALL },
	{ "SKILL", APPLY_SKILL },
	{ "BOW_DISTANCE", APPLY_BOW_DISTANCE },
	{ "ATT_GRADE_BONUS", APPLY_ATT_GRADE_BONUS },
	{ "DEF_GRADE_BONUS", APPLY_DEF_GRADE_BONUS },
	{ "MAGIC_ATT_GRADE", APPLY_MAGIC_ATT_GRADE },
	{ "MAGIC_DEF_GRADE", APPLY_MAGIC_DEF_GRADE },
	{ "CURSE_PCT", APPLY_CURSE_PCT },
	{ "MAX_STAMINA", APPLY_MAX_STAMINA },

	{ "ATTBONUS_WARRIOR", APPLY_ATTBONUS_WARRIOR },
	{ "ATTBONUS_ASSASSIN", APPLY_ATTBONUS_ASSASSIN },
	{ "ATTBONUS_SURA", APPLY_ATTBONUS_SURA },
	{ "ATTBONUS_SHAMAN", APPLY_ATTBONUS_SHAMAN },
	{ "ATTBONUS_MONSTER", APPLY_ATTBONUS_MONSTER },

	{ "MALL_ATTBONUS", APPLY_MALL_ATTBONUS },
	{ "MALL_DEFBONUS", APPLY_MALL_DEFBONUS },
	{ "MALL_EXPBONUS", APPLY_MALL_EXPBONUS },
	{ "MALL_ITEMBONUS", APPLY_MALL_ITEMBONUS },
	{ "MALL_GOLDBONUS", APPLY_MALL_GOLDBONUS },

	{ "MAX_HP_PCT", APPLY_MAX_HP_PCT },
	{ "MAX_SP_PCT", APPLY_MAX_SP_PCT },

	{ "SKILL_DAMAGE_BONUS", APPLY_SKILL_DAMAGE_BONUS },
	{ "NORMAL_HIT_DAMAGE_BONUS", APPLY_NORMAL_HIT_DAMAGE_BONUS },

	{ "SKILL_DEFEND_BONUS", APPLY_SKILL_DEFEND_BONUS },

	{ "NORMAL_HIT_DEFEND_BONUS", APPLY_NORMAL_HIT_DEFEND_BONUS },
	{ "PC_BANG_EXP_BONUS", APPLY_PC_BANG_EXP_BONUS },
	{ "PC_BANG_DROP_BONUS", APPLY_PC_BANG_DROP_BONUS },

	{ "EXTRACT_HP_PCT", APPLY_EXTRACT_HP_PCT },

	{ "RESIST_WARRIOR", APPLY_RESIST_WARRIOR },
	{ "RESIST_ASSASSIN", APPLY_RESIST_ASSASSIN },
	{ "RESIST_SURA", APPLY_RESIST_SURA },
	{ "RESIST_SHAMAN", APPLY_RESIST_SHAMAN },

	{ "ENERGY", APPLY_ENERGY },
	{ "DEF_GRADE", APPLY_DEF_GRADE },
	{ "COSTUME_ATTR_BONUS", APPLY_COSTUME_ATTR_BONUS },
	{ "MAGIC_ATTBONUS_PER", APPLY_MAGIC_ATTBONUS_PER },
	{ "MELEE_MAGIC_ATTBONUS_PER", APPLY_MELEE_MAGIC_ATTBONUS_PER },

	{ "RESIST_ICE", APPLY_RESIST_ICE },
	{ "RESIST_EARTH", APPLY_RESIST_EARTH },
	{ "RESIST_DARK", APPLY_RESIST_DARK },

	{ "RESIST_CRITICAL", APPLY_ANTI_CRITICAL_PCT /* APPLY_RESIST_CRITICAL */ },
	{ "RESIST_PENETRATE", APPLY_ANTI_PENETRATE_PCT /* APPLY_RESIST_PENETRATE */ },

	{ "BLEEDING_REDUCE", APPLY_BLEEDING_REDUCE },
	{ "BLEEDING_PCT", APPLY_BLEEDING_PCT },
	{ "ATTBONUS_WOLFMAN", APPLY_ATTBONUS_WOLFMAN },
	{ "RESIST_WOLFMAN", APPLY_RESIST_WOLFMAN },
	{ "RESIST_CLAW", APPLY_RESIST_CLAW },

	{ "ACCEDRAIN_RATE", APPLY_ACCEDRAIN_RATE },
	{ "RESIST_MAGIC_REDUCTION", APPLY_RESIST_MAGIC_REDUCTION },

	{ "ENCHANT_ELECT", APPLY_ENCHANT_ELECT },
	{ "ENCHANT_FIRE", APPLY_ENCHANT_FIRE },
	{ "ENCHANT_ICE", APPLY_ENCHANT_ICE },
	{ "ENCHANT_WIND", APPLY_ENCHANT_WIND },
	{ "ENCHANT_EARTH", APPLY_ENCHANT_EARTH },
	{ "ENCHANT_DARK", APPLY_ENCHANT_DARK },

	{ "ATTBONUS_CZ", APPLY_ATTBONUS_CZ },
	{ "ATTBONUS_INSECT", APPLY_ATTBONUS_INSECT },
	{ "ATTBONUS_DESERT", APPLY_ATTBONUS_DESERT },
	{ "ATTBONUS_SWORD", APPLY_ATTBONUS_SWORD },
	{ "ATTBONUS_TWOHAND", APPLY_ATTBONUS_TWOHAND },
	{ "ATTBONUS_DAGGER", APPLY_ATTBONUS_DAGGER },
	{ "ATTBONUS_BELL", APPLY_ATTBONUS_BELL },
	{ "ATTBONUS_FAN", APPLY_ATTBONUS_FAN },
	{ "ATTBONUS_BOW", APPLY_ATTBONUS_BOW },
	{ "ATTBONUS_CLAW", APPLY_ATTBONUS_CLAW },

	{ "RESIST_HUMAN", APPLY_RESIST_HUMAN },
	{ "RESIST_MOUNT_FALL", APPLY_RESIST_MOUNT_FALL },
	{ "RESIST_FIST", APPLY_RESIST_FIST },

	{ "MOUNT", APPLY_MOUNT },

	{ "SKILL_DAMAGE_SAMYEON", APPLY_SKILL_DAMAGE_SAMYEON },
	{ "SKILL_DAMAGE_TANHWAN", APPLY_SKILL_DAMAGE_TANHWAN },
	{ "SKILL_DAMAGE_PALBANG", APPLY_SKILL_DAMAGE_PALBANG },
	{ "SKILL_DAMAGE_GIGONGCHAM", APPLY_SKILL_DAMAGE_GIGONGCHAM },
	{ "SKILL_DAMAGE_GYOKSAN", APPLY_SKILL_DAMAGE_GYOKSAN },
	{ "SKILL_DAMAGE_GEOMPUNG", APPLY_SKILL_DAMAGE_GEOMPUNG },
	{ "SKILL_DAMAGE_AMSEOP", APPLY_SKILL_DAMAGE_AMSEOP },
	{ "SKILL_DAMAGE_GUNGSIN", APPLY_SKILL_DAMAGE_GUNGSIN },
	{ "SKILL_DAMAGE_CHARYUN", APPLY_SKILL_DAMAGE_CHARYUN },
	{ "SKILL_DAMAGE_SANGONG", APPLY_SKILL_DAMAGE_SANGONG },
	{ "SKILL_DAMAGE_YEONSA", APPLY_SKILL_DAMAGE_YEONSA },
	{ "SKILL_DAMAGE_KWANKYEOK", APPLY_SKILL_DAMAGE_KWANKYEOK },
	{ "SKILL_DAMAGE_GIGUNG", APPLY_SKILL_DAMAGE_GIGUNG },
	{ "SKILL_DAMAGE_HWAJO", APPLY_SKILL_DAMAGE_HWAJO },
	{ "SKILL_DAMAGE_SWAERYUNG", APPLY_SKILL_DAMAGE_SWAERYUNG },
	{ "SKILL_DAMAGE_YONGKWON", APPLY_SKILL_DAMAGE_YONGKWON },
	{ "SKILL_DAMAGE_PABEOB", APPLY_SKILL_DAMAGE_PABEOB },
	{ "SKILL_DAMAGE_MARYUNG", APPLY_SKILL_DAMAGE_MARYUNG },
	{ "SKILL_DAMAGE_HWAYEOMPOK", APPLY_SKILL_DAMAGE_HWAYEOMPOK },
	{ "SKILL_DAMAGE_MAHWAN", APPLY_SKILL_DAMAGE_MAHWAN },
	{ "SKILL_DAMAGE_BIPABU", APPLY_SKILL_DAMAGE_BIPABU },
	{ "SKILL_DAMAGE_YONGBI", APPLY_SKILL_DAMAGE_YONGBI },
	{ "SKILL_DAMAGE_PAERYONG", APPLY_SKILL_DAMAGE_PAERYONG },
	{ "SKILL_DAMAGE_NOEJEON", APPLY_SKILL_DAMAGE_NOEJEON },
	{ "SKILL_DAMAGE_BYEURAK", APPLY_SKILL_DAMAGE_BYEURAK },
	{ "SKILL_DAMAGE_CHAIN", APPLY_SKILL_DAMAGE_CHAIN },
	{ "SKILL_DAMAGE_CHAYEOL", APPLY_SKILL_DAMAGE_CHAYEOL },
	{ "SKILL_DAMAGE_SALPOONG", APPLY_SKILL_DAMAGE_SALPOONG },
	{ "SKILL_DAMAGE_GONGDAB", APPLY_SKILL_DAMAGE_GONGDAB },
	{ "SKILL_DAMAGE_PASWAE", APPLY_SKILL_DAMAGE_PASWAE },

	{ "NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE", APPLY_NORMAL_HIT_DEFEND_BONUS_BOSS_OR_MORE },
	{ "SKILL_DEFEND_BONUS_BOSS_OR_MORE", APPLY_SKILL_DEFEND_BONUS_BOSS_OR_MORE },
	{ "NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE", APPLY_NORMAL_HIT_DAMAGE_BONUS_BOSS_OR_MORE },
	{ "SKILL_DAMAGE_BONUS_BOSS_OR_MORE", APPLY_SKILL_DAMAGE_BONUS_BOSS_OR_MORE },

	{ "HIT_BUFF_ENCHANT_FIRE", APPLY_HIT_BUFF_ENCHANT_FIRE },
	{ "HIT_BUFF_ENCHANT_ICE", APPLY_HIT_BUFF_ENCHANT_ICE },
	{ "HIT_BUFF_ENCHANT_ELEC", APPLY_HIT_BUFF_ENCHANT_ELEC },
	{ "HIT_BUFF_ENCHANT_WIND", APPLY_HIT_BUFF_ENCHANT_WIND },
	{ "HIT_BUFF_ENCHANT_DARK", APPLY_HIT_BUFF_ENCHANT_DARK },
	{ "HIT_BUFF_ENCHANT_EARTH", APPLY_HIT_BUFF_ENCHANT_EARTH },
	{ "HIT_BUFF_RESIST_FIRE", APPLY_HIT_BUFF_RESIST_FIRE },
	{ "HIT_BUFF_RESIST_ICE", APPLY_HIT_BUFF_RESIST_ICE },
	{ "HIT_BUFF_RESIST_ELEC", APPLY_HIT_BUFF_RESIST_ELEC },
	{ "HIT_BUFF_RESIST_WIND", APPLY_HIT_BUFF_RESIST_WIND },
	{ "HIT_BUFF_RESIST_DARK", APPLY_HIT_BUFF_RESIST_DARK },
	{ "HIT_BUFF_RESIST_EARTH", APPLY_HIT_BUFF_RESIST_EARTH },

	{ "USE_SKILL_CHEONGRANG_MOV_SPEED", APPLY_USE_SKILL_CHEONGRANG_MOV_SPEED },
	{ "USE_SKILL_CHEONGRANG_CASTING_SPEED", APPLY_USE_SKILL_CHEONGRANG_CASTING_SPEED },
	{ "USE_SKILL_CHAYEOL_CRITICAL_PCT", APPLY_USE_SKILL_CHAYEOL_CRITICAL_PCT },
	{ "USE_SKILL_SANGONG_ATT_GRADE_BONUS", APPLY_USE_SKILL_SANGONG_ATT_GRADE_BONUS },
	{ "USE_SKILL_GIGUNG_ATT_GRADE_BONUS", APPLY_USE_SKILL_GIGUNG_ATT_GRADE_BONUS },
	{ "USE_SKILL_JEOKRANG_DEF_BONUS", APPLY_USE_SKILL_JEOKRANG_DEF_BONUS },
	{ "USE_SKILL_GWIGEOM_DEF_BONUS", APPLY_USE_SKILL_GWIGEOM_DEF_BONUS },
	{ "USE_SKILL_TERROR_ATT_GRADE_BONUS", APPLY_USE_SKILL_TERROR_ATT_GRADE_BONUS },
	{ "USE_SKILL_MUYEONG_ATT_GRADE_BONUS", APPLY_USE_SKILL_MUYEONG_ATT_GRADE_BONUS },
	{ "USE_SKILL_MANASHILED_CASTING_SPEED", APPLY_USE_SKILL_MANASHILED_CASTING_SPEED },
	{ "USE_SKILL_HOSIN_DEF_BONUS", APPLY_USE_SKILL_HOSIN_DEF_BONUS },
	{ "USE_SKILL_GICHEON_ATT_GRADE_BONUS", APPLY_USE_SKILL_GICHEON_ATT_GRADE_BONUS },
	{ "USE_SKILL_JEONGEOP_ATT_GRADE_BONUS", APPLY_USE_SKILL_JEONGEOP_ATT_GRADE_BONUS },
	{ "USE_SKILL_JEUNGRYEOK_DEF_BONUS", APPLY_USE_SKILL_JEUNGRYEOK_DEF_BONUS },
	{ "USE_SKILL_GIHYEOL_ATT_GRADE_BONUS", APPLY_USE_SKILL_GIHYEOL_ATT_GRADE_BONUS },
	{ "USE_SKILL_CHUNKEON_CASTING_SPEED", APPLY_USE_SKILL_CHUNKEON_CASTING_SPEED },
	{ "USE_SKILL_NOEGEOM_ATT_GRADE_BONUS", APPLY_USE_SKILL_NOEGEOM_ATT_GRADE_BONUS },

	{ "SKILL_DURATION_INCREASE_EUNHYUNG", APPLY_SKILL_DURATION_INCREASE_EUNHYUNG },
	{ "SKILL_DURATION_INCREASE_GYEONGGONG", APPLY_SKILL_DURATION_INCREASE_GYEONGGONG },
	{ "SKILL_DURATION_INCREASE_GEOMKYUNG", APPLY_SKILL_DURATION_INCREASE_GEOMKYUNG },
	{ "SKILL_DURATION_INCREASE_JEOKRANG", APPLY_SKILL_DURATION_INCREASE_JEOKRANG },

	{ "USE_SKILL_PALBANG_HP_ABSORB", APPLY_USE_SKILL_PALBANG_HP_ABSORB },
	{ "USE_SKILL_AMSEOP_HP_ABSORB", APPLY_USE_SKILL_AMSEOP_HP_ABSORB },
	{ "USE_SKILL_YEONSA_HP_ABSORB", APPLY_USE_SKILL_YEONSA_HP_ABSORB },
	{ "USE_SKILL_YONGBI_HP_ABSORB", APPLY_USE_SKILL_YONGBI_HP_ABSORB },
	{ "USE_SKILL_CHAIN_HP_ABSORB", APPLY_USE_SKILL_CHAIN_HP_ABSORB },
	{ "USE_SKILL_PASWAE_SP_ABSORB", APPLY_USE_SKILL_PASWAE_SP_ABSORB },

	{ "USE_SKILL_GIGONGCHAM_STUN", APPLY_USE_SKILL_GIGONGCHAM_STUN },
	{ "USE_SKILL_CHARYUN_STUN", APPLY_USE_SKILL_CHARYUN_STUN },
	{ "USE_SKILL_PABEOB_STUN", APPLY_USE_SKILL_PABEOB_STUN },
	{ "USE_SKILL_MAHWAN_STUN", APPLY_USE_SKILL_MAHWAN_STUN },
	{ "USE_SKILL_GONGDAB_STUN", APPLY_USE_SKILL_GONGDAB_STUN },
	{ "USE_SKILL_SAMYEON_STUN", APPLY_USE_SKILL_SAMYEON_STUN },

	{ "USE_SKILL_GYOKSAN_KNOCKBACK", APPLY_USE_SKILL_GYOKSAN_KNOCKBACK },
	{ "USE_SKILL_SEOMJEON_KNOCKBACK", APPLY_USE_SKILL_SEOMJEON_KNOCKBACK },
	{ "USE_SKILL_SWAERYUNG_KNOCKBACK", APPLY_USE_SKILL_SWAERYUNG_KNOCKBACK },
	{ "USE_SKILL_HWAYEOMPOK_KNOCKBACK", APPLY_USE_SKILL_HWAYEOMPOK_KNOCKBACK },
	{ "USE_SKILL_GONGDAB_KNOCKBACK", APPLY_USE_SKILL_GONGDAB_KNOCKBACK },
	{ "USE_SKILL_KWANKYEOK_KNOCKBACK", APPLY_USE_SKILL_KWANKYEOK_KNOCKBACK },

	{ "USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_10PER },
	{ "USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER", APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_10PER },

	{ "ATTBONUS_STONE", APPLY_ATTBONUS_STONE },

	{ "DAMAGE_HP_RECOVERY", APPLY_DAMAGE_HP_RECOVERY },
	{ "DAMAGE_SP_RECOVERY", APPLY_DAMAGE_SP_RECOVERY },

	{ "ALIGNMENT_DAMAGE_BONUS", APPLY_ALIGNMENT_DAMAGE_BONUS },

	{ "NORMAL_DAMAGE_GUARD", APPLY_NORMAL_DAMAGE_GUARD },
	{ "MORE_THEN_HP90_DAMAGE_REDUCE", APPLY_MORE_THEN_HP90_DAMAGE_REDUCE },

	{ "USE_SKILL_TUSOK_HP_ABSORB", APPLY_USE_SKILL_TUSOK_HP_ABSORB },
	{ "USE_SKILL_PAERYONG_HP_ABSORB", APPLY_USE_SKILL_PAERYONG_HP_ABSORB },
	{ "USE_SKILL_BYEURAK_HP_ABSORB", APPLY_USE_SKILL_BYEURAK_HP_ABSORB },

	{ "FIRST_ATTRIBUTE_BONUS", APPLY_FIRST_ATTRIBUTE_BONUS },
	{ "SECOND_ATTRIBUTE_BONUS", APPLY_SECOND_ATTRIBUTE_BONUS },
	{ "THIRD_ATTRIBUTE_BONUS", APPLY_THIRD_ATTRIBUTE_BONUS },
	{ "FOURTH_ATTRIBUTE_BONUS", APPLY_FOURTH_ATTRIBUTE_BONUS },
	{ "FIFTH_ATTRIBUTE_BONUS", APPLY_FIFTH_ATTRIBUTE_BONUS },

	{ "USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_SAMYEON_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_GEOMPUNG_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_GUNGSIN_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_KWANKYEOK_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_YONGKWON_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_MARYUNG_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_BIPABU_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_NOEJEON_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_SALPOONG_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER", APPLY_USE_SKILL_PASWAE_NEXT_COOLTIME_DECREASE_20PER },
	{ "USE_SKILL_CHAYEOL_HP_ABSORB", APPLY_USE_SKILL_CHAYEOL_HP_ABSORB },

	{ "SUNGMA_STR", APPLY_SUNGMA_STR },
	{ "SUNGMA_HP", APPLY_SUNGMA_HP },
	{ "SUNGMA_MOVE", APPLY_SUNGMA_MOVE },
	{ "SUNGMA_IMMUNE", APPLY_SUNGMA_IMMUNE },

	{ "HIT_PCT", APPLY_HIT_PCT },
#if defined(__ITEM_APPLY_RANDOM__)
	{ "RANDOM", APPLY_NONE },
#endif

	{ "ATTBONUS_PER_HUMAN", APPLY_ATTBONUS_PER_HUMAN },
	{ "ATTBONUS_PER_ANIMAL", APPLY_ATTBONUS_PER_ANIMAL },
	{ "ATTBONUS_PER_ORC", APPLY_ATTBONUS_PER_ORC },
	{ "ATTBONUS_PER_MILGYO", APPLY_ATTBONUS_PER_MILGYO },
	{ "ATTBONUS_PER_UNDEAD", APPLY_ATTBONUS_PER_UNDEAD },
	{ "ATTBONUS_PER_DEVIL", APPLY_ATTBONUS_PER_DEVIL },

	{ "ENCHANT_PER_ELECT", APPLY_ENCHANT_PER_ELECT },
	{ "ENCHANT_PER_FIRE", APPLY_ENCHANT_PER_FIRE },
	{ "ENCHANT_PER_ICE", APPLY_ENCHANT_PER_ICE },
	{ "ENCHANT_PER_WIND", APPLY_ENCHANT_PER_WIND },
	{ "ENCHANT_PER_EARTH", APPLY_ENCHANT_PER_EARTH },
	{ "ENCHANT_PER_DARK", APPLY_ENCHANT_PER_DARK },

	{ "ATTBONUS_PER_CZ", APPLY_ATTBONUS_PER_CZ },
	{ "ATTBONUS_PER_INSECT", APPLY_ATTBONUS_PER_INSECT },
	{ "ATTBONUS_PER_DESERT", APPLY_ATTBONUS_PER_DESERT },
	{ "ATTBONUS_PER_STONE", APPLY_ATTBONUS_PER_STONE },
	{ "ATTBONUS_PER_MONSTER", APPLY_ATTBONUS_PER_MONSTER },

	{ "RESIST_PER_HUMAN", APPLY_RESIST_PER_HUMAN },
	{ "RESIST_PER_ICE", APPLY_RESIST_PER_ICE },
	{ "RESIST_PER_DARK", APPLY_RESIST_PER_DARK },
	{ "RESIST_PER_EARTH", APPLY_RESIST_PER_EARTH },
	{ "RESIST_PER_FIRE", APPLY_RESIST_PER_FIRE },
	{ "RESIST_PER_ELEC", APPLY_RESIST_PER_ELEC },
	{ "RESIST_PER_MAGIC", APPLY_RESIST_PER_MAGIC },
	{ "RESIST_PER_WIND", APPLY_RESIST_PER_WIND },

	{ "HIT_BUFF_SUNGMA_STR", APPLY_HIT_BUFF_SUNGMA_STR },
	{ "HIT_BUFF_SUNGMA_MOVE", APPLY_HIT_BUFF_SUNGMA_MOVE },
	{ "HIT_BUFF_SUNGMA_HP", APPLY_HIT_BUFF_SUNGMA_HP },
	{ "HIT_BUFF_SUNGMA_IMMUNE", APPLY_HIT_BUFF_SUNGMA_IMMUNE },

	{ "MOUNT_MELEE_MAGIC_ATTBONUS_PER", APPLY_MOUNT_MELEE_MAGIC_ATTBONUS_PER },
	{ "DISMOUNT_MOVE_SPEED_BONUS_PER", APPLY_DISMOUNT_MOVE_SPEED_BONUS_PER },

	{ "HIT_AUTO_HP_RECOVERY", APPLY_HIT_AUTO_HP_RECOVERY },
	{ "HIT_AUTO_SP_RECOVERY", APPLY_HIT_AUTO_SP_RECOVERY },

	{ "USE_SKILL_COOLTIME_DECREASE_ALL", APPLY_USE_SKILL_COOLTIME_DECREASE_ALL },

	{ "HIT_STONE_ATTBONUS_STONE", APPLY_HIT_STONE_ATTBONUS_STONE },
	{ "HIT_STONE_DEF_GRADE_BONUS", APPLY_HIT_STONE_DEF_GRADE_BONUS },

	{ "KILL_BOSS_ITEM_BONUS", APPLY_KILL_BOSS_ITEM_BONUS },
	{ "MOB_HIT_MOB_AGGRESSIVE", APPLY_MOB_HIT_MOB_AGGRESSIVE },
	{ "NO_DEATH_AND_HP_RECOVERY30", APPLY_NO_DEATH_AND_HP_RECOVERY30 },

	{ "AUTO_PICKUP", APPLY_AUTO_PICKUP },
	{ "MOUNT_NO_KNOCKBACK", APPLY_MOUNT_NO_KNOCKBACK },

	{ "SUNGMA_PER_STR", APPLY_SUNGMA_PER_STR },
	{ "SUNGMA_PER_HP", APPLY_SUNGMA_PER_HP },
	{ "SUNGMA_PER_MOVE", APPLY_SUNGMA_PER_MOVE },
	{ "SUNGMA_PER_IMMUNE", APPLY_SUNGMA_PER_IMMUNE },

	{ "IMMUNE_POISON100", APPLY_IMMUNE_POISON100 },
	{ "IMMUNE_BLEEDING100", APPLY_IMMUNE_BLEEDING100 },

	{ "MONSTER_DEFEND_BONUS", APPLY_MONSTER_DEFEND_BONUS },

	// by mhh game/affect.h 정의되어있음. INFINITE_AFFECT_DURATION = 0x1FFFFFFF
	{ "INFINITE_AFFECT_DURATION", 0x1FFFFFFF },

	// 20200806.Owsap : Old apply values support.
	{ "ATTACK_SPEED", APPLY_ATT_SPEED },
	{ "MOVE_SPEED", APPLY_MOV_SPEED },
	{ "ATT_BONUS", APPLY_ATT_GRADE_BONUS },
	{ "DEF_BONUS", APPLY_DEF_GRADE_BONUS },
	{ "ATT_BONUS_TO_WARRIOR", APPLY_ATTBONUS_WARRIOR },
	{ "ATT_BONUS_TO_ASSASSIN", APPLY_ATTBONUS_ASSASSIN },
	{ "ATT_BONUS_TO_SURA", APPLY_ATTBONUS_SURA },
	{ "ATT_BONUS_TO_SHAMAN", APPLY_ATTBONUS_SHAMAN },
	{ "ATT_BONUS_TO_WOLFMAN", APPLY_ATTBONUS_WOLFMAN },

	{ NULL, 0 }
};
// from import_item_proto.c

long FN_get_apply_type(const char* apply_type_string)
{
	TValueName* value_name;
	for (value_name = c_aApplyTypeNames; value_name->c_pszName; ++value_name)
	{
		if (0 == strcasecmp(value_name->c_pszName, apply_type_string))
			return value_name->lValue;
	}
	return 0;
}

#if defined(__SOUL_SYSTEM__)
const int soul_refine_prob[SOUL_GRADE_MAX + 1] = { 0, 60, 40, 20, 30, 15 };
#endif

#if defined(__EXTEND_INVEN_SYSTEM__)
/*
* By hard coding the required keys, the code becomes more readable
* and maintainable, as anyone reading the code can immediately can
* immediately see the requiremented keys for each stage.
*/
const BYTE abInvenStageKeys[EX_INVENTORY_STAGE_MAX] =
{
	// 90 - 135
	2, 2, 2,
	3, 3, 3,
	4, 4, 4,
	// 135 - 180
	5, 5, 5,
	6, 6, 6,
	7, 7, 7
};
#endif

TEmotionInfoMap EmotionInfoMap
{
	{ EMOTION_NONE, { 0, 0.0f } },
	{ EMOTION_CLAP, { EMOTION_FLAG_SELF, 2.66667f } },
	{ EMOTION_CONGRATULATION, { EMOTION_FLAG_SELF, 6.33333f } },
	{ EMOTION_FORGIVE, { EMOTION_FLAG_SELF, 8.33333f } },
	{ EMOTION_ANGRY, { EMOTION_FLAG_SELF, 4.33333f } },
	{ EMOTION_ATTRACTIVE, { EMOTION_FLAG_SELF, 4.83333f } },
	{ EMOTION_SAD, { EMOTION_FLAG_SELF, 7.33333f } },
	{ EMOTION_SHY, { EMOTION_FLAG_SELF, 4.66667f } },
	{ EMOTION_CHEERUP, { EMOTION_FLAG_SELF, 5.0f } },
	{ EMOTION_BANTER, { EMOTION_FLAG_SELF, 7.0f } },
	{ EMOTION_JOY, { EMOTION_FLAG_SELF, 5.33333f } },
	{ EMOTION_CHEERS_1, { EMOTION_FLAG_SELF, 2.33333f } },
	{ EMOTION_CHEERS_2, { EMOTION_FLAG_SELF, 2.33333f } },
	{ EMOTION_DANCE_1, { EMOTION_FLAG_SELF, 28.3333f } },
	{ EMOTION_DANCE_2, { EMOTION_FLAG_SELF, 4.76667f } },
	{ EMOTION_DANCE_3, { EMOTION_FLAG_SELF, 27.3333f } },
	{ EMOTION_DANCE_4, { EMOTION_FLAG_SELF, 30.3333f } },
	{ EMOTION_DANCE_5, { EMOTION_FLAG_SELF, 21.1f } },
	{ EMOTION_DANCE_6, { EMOTION_FLAG_SELF, 30.433332f } },
	{ EMOTION_KISS, { EMOTION_FLAG_TARGET | EMOTION_FLAG_OTHER_SEX, 1.5f } },
	{ EMOTION_FRENCH_KISS, { EMOTION_FLAG_TARGET | EMOTION_FLAG_OTHER_SEX, 4.0f } },
	{ EMOTION_SLAP, { EMOTION_FLAG_TARGET, 2.0f } },
#if defined(__EXPRESSING_EMOTIONS__)
	{ EMOTION_PUSH_UP, { EMOTION_FLAG_SELF, 6.666667f } },
	{ EMOTION_DANCE_7, { EMOTION_FLAG_SELF, 12.0f } },
	{ EMOTION_EXERCISE, { EMOTION_FLAG_SELF, 6.333333f } },
	{ EMOTION_DOZE, { EMOTION_FLAG_SELF, 4.666667f } },
	{ EMOTION_SELFIE, { EMOTION_FLAG_SELF, 3.000000f } },
	{ EMOTION_CHARGING, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_NOSAY, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_WEATHER_1, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_WEATHER_2, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_WEATHER_3, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_HUNGRY, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_SIREN, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_LETTER, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_CALL, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_CELEBRATION, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_ALCOHOL, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_BUSY, { EMOTION_FLAG_SELF, 0.0f } },
	{ EMOTION_WHIRL, { EMOTION_FLAG_SELF, 0.0f } },
#endif
};

#if defined(__HIDE_COSTUME_SYSTEM__)
THiddenCostumePartMap HiddenCostumePartMap
{
	{ COSTUME_BODY, "costume_option.hide_body" },
	{ COSTUME_HAIR, "costume_option.hide_hair" },
#if defined(__ACCE_COSTUME_SYSTEM__)
	{ COSTUME_ACCE, "costume_option.hide_acce" },
#endif
#if defined(__WEAPON_COSTUME_SYSTEM__)
	{ COSTUME_WEAPON, "costume_option.hide_weapon" },
#endif
#if defined(__AURA_COSTUME_SYSTEM__)
	{ COSTUME_AURA, "costume_option.hide_aura" },
#endif
};
#endif
